blueprint:
  domain: automation
  name: "Alexa Presence-Aware Radio Stop – Music Assistant"
  author: madalone
  description: |
    ![Image](/local/blueprint-images/alexa_presence_radio_stop-header.jpeg)

    # Stop radio playback from any Alexa — one command

    Say "stop the music" (or any phrase you configure) to **any** Alexa
    device in your home. Home Assistant stops all configured Music Assistant
    players, or optionally only the player in the room where you currently
    have presence.

    ### How it works

    ```
    "Alexa, turn on Stop Radio"  (from ANY Echo)
            │
            ▼
    input_boolean.radio_stop → ON
            │
            ▼
    This automation fires
            │
            ├── Stop all mode:  stops every configured MA player
            └── Presence mode:  checks sensors → stops only that room's player
            │
            ▼
    Boolean auto-resets to OFF → ready for next command
    ```

    ### Setup

    #### 1. Create an input_boolean helper

    Settings → Devices & Services → Helpers → **Toggle**

    Name it something like "Stop Radio" → creates `input_boolean.stop_radio`.

    #### 2. Expose to Alexa

    Settings → Home Assistant Cloud → Alexa → find your toggle → switch ON.

    #### 3. Create ONE Alexa Routine

    In the Alexa app → More → Routines → +

    * **When:** Voice → "Stop the music" (or "Shut up", "Silence", etc.)
    * **From:** All devices
    * **Action:** Smart Home → toggle ON `Stop Radio`

    ### Companion blueprints

    Use alongside the **Alexa Presence-Aware Radio** blueprint for a
    complete voice-controlled radio system.

    ### Recent changes
    - **v3:** Template safety (AP-16 `| default()` on states()), §3.2 section naming/dividers, added explicit `conditions: []`
    - **v2:** Style guide compliance — aliases on all actions, collapsible input sections, author field, changelog, custom header image
    - **v1:** Initial version

  homeassistant:
    min_version: 2024.10.0

  input:
    # ===========================================================================
    # ① TRIGGER
    # ===========================================================================
    trigger_settings:
      name: "① Trigger"
      icon: mdi:toggle-switch
      description: The input_boolean that fires this automation when Alexa turns it ON.
      input:
        trigger_entity:
          name: Trigger entity (input_boolean)
          description: >
            The input_boolean helper that triggers this automation when turned ON.


            Create one in Settings → Devices & Services → Helpers → Toggle.
            Expose it to Alexa via HA Cloud, then create a single Alexa Routine
            with your stop phrase that turns this toggle ON.
          selector:
            entity:
              domain: input_boolean

    # ===========================================================================
    # ② PLAYER SELECTION
    # ===========================================================================
    player_selection:
      name: "② Player selection"
      icon: mdi:speaker-group
      description: Which Music Assistant players can be stopped by this automation.
      input:
        players_to_stop:
          name: Music Assistant players to stop
          description: >
            All Music Assistant players that should be stopped. In "stop all"
            mode, every player in this list is stopped. In "presence-aware"
            mode, only the player mapped to your current room is stopped.
          selector:
            entity:
              filter:
                - integration: music_assistant
                  domain:
                    - media_player
              multiple: true

    # ===========================================================================
    # ③ STOP MODE
    # ===========================================================================
    stop_mode:
      name: "③ Stop mode"
      icon: mdi:stop-circle-outline
      description: >
        Choose between stopping all players or only the player in the
        room where you currently are.
      input:
        presence_aware_stop:
          name: Presence-aware stop (only stop current room)
          description: >
            If enabled, only the player in the room where presence is
            detected will be stopped. Requires presence sensors and
            player mapping below.


            If disabled, ALL configured players are stopped regardless
            of where you are.
          default: false
          selector:
            boolean: {}

        presence_sensors:
          name: Presence sensors (same order as players above)
          description: >
            Binary sensors mapped 1:1 with the players list above.
            First sensor = first player, second = second, etc.


            Only used when "Presence-aware stop" is enabled.


            **The order must exactly match the players list.**


            If your play blueprint uses duplicate players for multi-zone
            mapping, replicate the same sensor/player order here.
          default: []
          selector:
            entity:
              domain: binary_sensor
              multiple: true

    # ===========================================================================
    # ④ BEHAVIOUR
    # ===========================================================================
    behaviour:
      name: "④ Behaviour"
      icon: mdi:shield-check-outline
      description: Additional behaviour options.
      collapsed: true
      input:
        auto_off_trigger:
          name: Automatically turn off trigger after stopping
          description: >
            Turns the input_boolean back OFF after stopping, so it's
            ready for the next voice command. Recommended.
          default: true
          selector:
            boolean: {}

        also_pause_instead_of_stop:
          name: Pause instead of stop
          description: >
            If enabled, players will be paused instead of stopped.
            This preserves the queue so playback can be resumed later.
          default: false
          selector:
            boolean: {}

        turn_off_radio_booleans:
          name: Also turn off radio trigger booleans
          description: >
            If enabled, the selected input_boolean helpers will also
            be turned off when stopping. Useful to reset the state of
            your radio dispatch triggers.
          default: false
          selector:
            boolean: {}

        radio_booleans:
          name: Radio trigger booleans to reset
          description: >
            Input_boolean entities used by your radio dispatch
            automations. Only used when "Also turn off radio trigger
            booleans" is enabled.
          default: []
          selector:
            entity:
              domain: input_boolean
              multiple: true

triggers:
  - alias: "Input boolean trigger turned ON"
    trigger: state
    entity_id: !input trigger_entity
    to: "on"

conditions: []

# ---------------------------------------------------------------------------
# Variables — resolve inputs and compute presence-aware stop targets
# ---------------------------------------------------------------------------
variables:
  player_list: !input players_to_stop
  presence_aware_flag: !input presence_aware_stop
  presence_list: !input presence_sensors
  auto_off_flag: !input auto_off_trigger
  pause_flag: !input also_pause_instead_of_stop
  reset_booleans_flag: !input turn_off_radio_booleans
  radio_booleans_list: !input radio_booleans

  detected_index: >
    {% set ns = namespace(idx=-1) %}
    {% for sensor in presence_list %}
      {% if ns.idx == -1 and states(sensor) | default('off') == 'on' %}
        {% set ns.idx = loop.index0 %}
      {% endif %}
    {% endfor %}
    {{ ns.idx }}

  stop_targets: >
    {% if presence_aware_flag and presence_list | length > 0 %}
      {% set idx = detected_index | int(-1) %}
      {% if idx >= 0 and idx < player_list | length %}
        {{ [player_list[idx]] }}
      {% else %}
        {{ player_list }}
      {% endif %}
    {% else %}
      {{ player_list }}
    {% endif %}

# ---------------------------------------------------------------------------
# Actions
# ---------------------------------------------------------------------------
actions:
  - alias: "Auto-reset trigger boolean — must happen first so next command works even if stop fails"
    choose:
      - alias: "Auto-off enabled — reset the input_boolean"
        conditions:
          - condition: template
            value_template: "{{ auto_off_flag }}"
        sequence:
          - alias: "Turn off trigger boolean"
            action: input_boolean.turn_off
            target:
              entity_id: !input trigger_entity

  - alias: "Stop or pause target players based on user preference"
    choose:
      - alias: "Pause mode — preserve queue for later resume"
        conditions:
          - condition: template
            value_template: "{{ pause_flag }}"
        sequence:
          - alias: "Pause target players"
            action: media_player.media_pause
            target:
              entity_id: "{{ stop_targets }}"
    default:
      - alias: "Stop target players"
        action: media_player.media_stop
        target:
          entity_id: "{{ stop_targets }}"

  - alias: "Reset companion radio dispatch booleans if configured"
    choose:
      - alias: "Reset enabled and booleans configured — turn them off"
        conditions:
          - condition: template
            value_template: >
              {{ reset_booleans_flag and radio_booleans_list | length > 0 }}
        sequence:
          - alias: "Turn off radio dispatch booleans"
            action: input_boolean.turn_off
            target:
              entity_id: "{{ radio_booleans_list }}"

mode: single
max_exceeded: silent
