blueprint:
  name: Announce Music Follow Me (TTS, LLM)
  description: |
    Announces via TTS where the music was moved for a "music follow me"
    automation.

  domain: script

  input:
    tts_entity:
      name: TTS entity
      selector:
        entity:
          domain: tts

    use_random_messages:
      name: Use random fun messages
      default: true
      selector:
        boolean: {}

    use_llm_fun_messages:
      name: Use LLM for fun messages
      default: false
      selector:
        boolean: {}

    use_playback_context:
      name: Include playback context in LLM prompt
      default: true
      selector:
        boolean: {}

    llm_prompt_template:
      name: LLM prompt template
      default: >
        You are a casual smart home assistant.
        Say the music moved to "{player_name}" and briefly comment on it.
        Time: {current_time}, {time_of_day}.
      selector:
        text:
          multiline: true

    llm_agent_id:
      name: Conversation persona (Extended OpenAI)
      default: ""
      selector:
        entity:
          domain: conversation

    custom_random_messages:
      name: Random messages
      default:
        - "Moving the music to {player_name}."
        - "Music transferred to {player_name}."
        - "Playback moved to {player_name}."
      selector:
        object: {}

    default_message:
      name: Default message
      default: "Moving the music to {player_name}."
      selector:
        text:
          multiline: true

    elevenlabs_voice:
      name: ElevenLabs voice
      default: ""
      selector:
        text: {}

    elevenlabs_voice_profile:
      name: ElevenLabs voice profile
      default: ""
      selector:
        text: {}

mode: queued
max_exceeded: silent

fields:
  target_player:
    name: Target player
    required: true
    selector:
      entity:
        domain: media_player

  source_player:
    name: Source player
    required: false
    selector:
      entity:
        domain: media_player

  tts_output_player:
    name: TTS output player (optional)
    required: false
    selector:
      entity:
        domain: media_player

variables:
  tts_entity_id: !input tts_entity
  random_mode: !input use_random_messages
  use_llm: !input use_llm_fun_messages
  use_context: !input use_playback_context
  llm_agent: !input llm_agent_id
  prompt_tpl: !input llm_prompt_template
  default_msg_tpl: !input default_message
  custom_msgs: !input custom_random_messages
  el_voice: !input elevenlabs_voice
  el_voice_profile: !input elevenlabs_voice_profile

sequence:
  # Resolve names and time
  - variables:
      player_name: "{{ state_attr(target_player,'friendly_name') or target_player }}"
      ctx_player: "{{ source_player if source_player is defined and source_player else target_player }}"
      media_title: "{{ state_attr(ctx_player,'media_title') | default('',true) }}"
      media_artist: "{{ state_attr(ctx_player,'media_artist') | default('',true) }}"
      current_time: "{{ now().strftime('%H:%M') }}"
      time_of_day: >
        {% set h = now().hour %}
        {% if h < 6 %}late night
        {% elif h < 12 %}morning
        {% elif h < 18 %}afternoon
        {% else %}evening
        {% endif %}

  # Decide message
  - choose:
      # LLM path
      - conditions:
          - condition: template
            value_template: "{{ random_mode and use_llm }}"
        sequence:
          - service: conversation.process
            data:
              agent_id: "{{ llm_agent or omit }}"
              text: >
                  {{
                    prompt_tpl
                    | replace('{player_name}', player_name)
                    | replace('{current_time}', current_time)
                    | replace('{time_of_day}', time_of_day)
                  }}
                  {% if use_context and media_title %}
                  {% if 'radio' in media_title | lower or 'radio' in media_artist | lower %}
                  currently tuned to the radio station "{{ media_title }}"{% if media_artist %} ({{ media_artist }}){% endif %}. this is a live radio stream, not a song or track.
                  {% else %}
                  currently playing the track "{{ media_title }}"{% if media_artist %} by {{ media_artist }}{% endif %}.
                  {% endif %}
                  {% endif %}
            response_variable: llm_response
            continue_on_error: true

          - variables:
              tts_message: >
                {% set r = llm_response | default({}) %}
                {% set resp = r.response | default({}) %}
                {% if resp.speech is defined
                      and resp.speech.plain is defined
                      and resp.speech.plain.speech is defined %}
                  {{ resp.speech.plain.speech | trim }}
                {% elif resp.text is defined %}
                  {{ resp.text | trim }}
                {% else %}
                  {{ default_msg_tpl | replace('{player_name}', player_name) }}
                {% endif %}

      # Static random path
      - conditions:
          - condition: template
            value_template: "{{ random_mode and not use_llm }}"
        sequence:
          - variables:
              tts_message: >
                {{
                  custom_msgs | random
                  | replace('{player_name}', player_name)
                }}

    default:
      - variables:
          tts_message: >
            {{ default_msg_tpl | replace('{player_name}', player_name) }}

  # Speak
  - service: tts.speak
    target:
      entity_id: "{{ tts_entity_id }}"
    data:
      media_player_entity_id: >
        {{ tts_output_player if tts_output_player is defined and tts_output_player else target_player }}


      message: "{{ tts_message }}"
      options:
        voice: "{{ el_voice if el_voice and not el_voice_profile else omit }}"
        voice_profile: "{{ el_voice_profile if el_voice_profile else omit }}"
