blueprint:
  name: Alarm with LLM context (clean)
  description: |
    Alarm that:
      - triggers ONLY on time + selected weekdays
      - does NOT use presence sensors as triggers or conditions
      - can optionally feed any selected entities into the LLM as sensor_context
      - plays a TTS wake-up message (static or LLM-generated)
      - optionally sends a mobile notification with Snooze/Stop buttons
      - allows ONE snooze; after that it either stops or starts your wake-up music script

    FLOW
    ----
    1. At wakeup_time on active_days the alarm always fires.
    2. Sets TTS player volume.
    3. Prepares a default wake_message (from the static text input).
    4. If LLM is enabled (use_llm_wake_message + agent_id):
         - Builds a sensor_context string from llm_context_entities.
         - Calls conversation.process with your prompt + sensor_context + time meta.
         - Uses the agent's response as wake_message (fallback is static text).
    5. Sends a mobile notification with Snooze/Stop actions (if notify_service is set).
    6. Speaks wake_message.
    7. Waits post_tts_timeout seconds for a mobile Snooze/Stop action:
         - STOP in first window:
             - instantly media_stop on TTS player
             - restore volume
             - end, no music.
         - SNOOZE in first window:
             - instantly media_stop on TTS player
             - wait snooze_minutes
             - speak again
             - wait again only for STOP (post_tts_timeout)
             - STOP after snooze:
                 - media_stop (belt & braces)
                 - restore volume
                 - end, no music.
             - nothing after snooze:
                 - run music_script, restore volume, end.
         - nothing in first window:
             - run music_script, restore volume, end.

    NOTES
    -----
    * llm_context_entities are ONLY used for LLM context; they do not gate the alarm.
    * voice_profile is passed via options.voice_profile into tts.speak ONLY when non-empty,
      so the blueprint works with any TTS engine (ElevenLabs, Google, etc.).
    * You must configure your mobile app notification actions so that:
        - one action matches mobile_snooze_action_id
        - one action matches mobile_stop_action_id
      and the app sends mobile_app_notification_action events.

  domain: automation
  source_url: https://example.local/blueprints/wake-up-guard-llm-time.yaml
  input:
    active_days:
      name: Active weekdays
      description: Days on which this wake-up should run.
      default:
        - mon
        - tue
        - wed
        - thu
        - fri
      selector:
        select:
          multiple: true
          mode: list
          options:
            - label: Monday
              value: mon
            - label: Tuesday
              value: tue
            - label: Wednesday
              value: wed
            - label: Thursday
              value: thu
            - label: Friday
              value: fri
            - label: Saturday
              value: sat
            - label: Sunday
              value: sun

    wakeup_entities:
      name: Wake-up lights / switches (optional)
      description: Select lights and/or switches to turn on when the alarm starts.
      default: []
      selector:
        entity:
          domain:
            - light
            - switch
          multiple: true

    wakeup_time:
      name: Wake-up time
      description: Time at which the wake-up guard should fire.
      selector:
        time: {}

    tts_engine:
      name: TTS engine
      description: TTS entity to use with tts.speak.
      selector:
        entity:
          domain: tts

    tts_output_player:
      name: TTS output media_player
      description: media_player where the TTS wake-up announcement will play.
      selector:
        entity:
          domain: media_player

    tts_volume_before:
      name: TTS volume before wake-up
      description: Volume level for TTS before the wake-up message is played.
      default: 0.4
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01
          mode: slider

    tts_volume_after:
      name: TTS volume after wake-up
      description: Volume level to restore on the TTS player after the wake-up flow completes.
      default: 0.4
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01
          mode: slider

    voice_profile:
      name: ElevenLabs voice_profile (optional)
      description: >
        Optional voice_profile value for your ElevenLabs / custom TTS integration.
        Passed inside options to tts.speak so you can switch between profiles
        like "Rick Sanchez - Custom 11 v0.1.2", "Quark", etc. Copy from ElevenLabs dashboard, case-sensitive
      default: ""
      selector:
        text: {}

    tts_message:
      name: Static wake-up message text
      description: >
        Static wake-up message text if you are not using the LLM, or as a fallback
        if the LLM call fails.
      default: "good morning miquel, time to get up."
      selector:
        text:
          multiline: true

    use_llm_wake_message:
      name: Use LLM for wake-up rant
      description: >
        If on, the wake-up rant will be generated on the fly by your conversation agent,
        using the prompt + sensor data as context.
        If off, only the static wake-up message text is used.
      default: false
      selector:
        boolean: {}

    llm_agent:
      name: Conversation agent
      description: >
        Select the Home Assistant conversation agent that should generate
        the wake-up message (for example: OpenAI, Local LLM, etc.).
      selector:
        entity:
          domain: conversation

    llm_wake_prompt:
      name: LLM wake-up prompt
      description: >
        Prompt sent to the conversation agent to generate the rant.

        The automation will append:
          - current time (24h + 12h plain)
          - configured wakeup time
          - snooze_stop_window_seconds
          - sensor_context (from llm_context_entities)
      default: ""
      selector:
        text:
          multiline: true

    llm_context_entities:
      name: Entities for LLM sensor_context (optional)
      description: >
        Optional extra entities to feed into the LLM as sensor_context
        (for example temperature sensors, persons, switches, presence sensors, etc.).
        These are NEVER used as triggers or conditions, only as context text.
      default: []
      selector:
        entity:
          multiple: true

    post_tts_timeout:
      name: Snooze/Stop listening window (seconds)
      description: >
        Number of seconds after the wake-up announcement starts during which
        the automation will watch for Snooze/Stop.
        Also used to size the rant length (approx) when using the LLM.
      default: 40
      selector:
        number:
          min: 1
          max: 600
          unit_of_measurement: s
          mode: slider

    snooze_minutes:
      name: Snooze minutes (max one snooze)
      description: >
        Minutes to wait after Snooze before repeating the wake-up TTS once.
      default: 7
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min
          mode: slider

    music_script:
      name: Wake-up music script
      description: >
        Script to call when wake-up is complete (no Snooze, or after snooze).
        This script should start your wake-up music, or hand over to a helper script.
      selector:
        entity:
          domain: script

    notify_service:
      name: Notify service
      description: >
        Notify service to use for the mobile notification, for example:
          notify.mobile_app_madaringer
        Leave empty to disable notifications.
      default: ""
      selector:
        text: {}

    mobile_snooze_action_id:
      name: Mobile Snooze action id
      description: >
        Action id used by your mobile app for the Snooze button.
        The app must send mobile_app_notification_action with this action value.
      default: "GUARD_SNOOZE"
      selector:
        text: {}

    mobile_stop_action_id:
      name: Mobile Stop action id
      description: >
        Action id used by your mobile app for the Stop button.
        The app must send mobile_app_notification_action with this action value.
      default: "GUARD_STOP"
      selector:
        text: {}

mode: single
max_exceeded: silent

variables:
  v_active_days: !input active_days
  v_use_llm_wake: !input use_llm_wake_message
  v_llm_agent: !input llm_agent
  v_llm_wake_prompt: !input llm_wake_prompt
  v_llm_context_entities: !input llm_context_entities
  v_notify_service: !input notify_service
  v_mobile_snooze_action_id: !input mobile_snooze_action_id
  v_mobile_stop_action_id: !input mobile_stop_action_id
  v_post_tts_timeout: !input post_tts_timeout
  v_snooze_minutes: !input snooze_minutes
  v_wakeup_time: !input wakeup_time
  v_voice_profile: !input voice_profile

trigger:
  - alias: "Wake-up time"
    platform: time
    at: !input wakeup_time

condition:
  - alias: "Today is in active_days"
    condition: template
    value_template: >
      {% set idx = now().weekday() %}
      {% set map = ['mon','tue','wed','thu','fri','sat','sun'] %}
      {{ map[idx] in v_active_days }}

action:

  - alias: "Turn on wake-up lights / switches"
    service: homeassistant.turn_on
    target:
      entity_id: !input wakeup_entities

  - alias: "Set TTS volume before wake-up"
    service: media_player.volume_set
    target:
      entity_id: !input tts_output_player
    data:
      volume_level: !input tts_volume_before

  - alias: "Default wake message"
    variables:
      wake_message: !input tts_message

  - alias: "Build sensor context for LLM"
    variables:
      sensor_context: >
        {% set entities = expand(v_llm_context_entities | default([])) %}
        {% if entities | length == 0 %}
          no extra sensor data
        {% else %}
          {% set ns = namespace(lines=[]) %}
          {% for e in entities %}
            {% set ns.lines = ns.lines + [e.entity_id ~ ' (' ~ (e.name or e.entity_id) ~ '): ' ~ e.state] %}
          {% endfor %}
          {{ ns.lines | join(' | ') }}
        {% endif %}

  - alias: "Optionally generate wake message via LLM"
    choose:
      - conditions:
          - condition: template
            value_template: >
              {{ v_use_llm_wake and v_llm_agent is string and v_llm_agent | length > 0 }}
        sequence:
          - service: conversation.process
            data:
              agent_id: "{{ v_llm_agent }}"
              text: >
                {{ (v_llm_wake_prompt | default('') | string)
                   ~ '\n\nmeta:\n'
                   ~ '- current_time_24h: ' ~ now().strftime('%H:%M') ~ '\n'
                   ~ '- current_time_12h_plain: ' ~ now().strftime('%I:%M').lstrip('0') ~ '\n'
                   ~ '- configured_wakeup_time: ' ~ (v_wakeup_time | string) ~ '\n'
                   ~ '- snooze_stop_window_seconds: ' ~ (v_post_tts_timeout | string) ~ '\n'
                   ~ 'assume you speak about roughly 2 words per second. aim for about '
                   ~ ((v_post_tts_timeout * 2) | int | string)
                   ~ ' words in total and do not go much longer than that.'
                   ~ '\n\nwhen you mention the time to miquel, use current_time_12h_plain and write it like "9:29".'
                   ~ ' do not add am or pm and do not use 24-hour format.'
                   ~ '\n\ncontext:\n'
                   ~ '- wakeup_reason: alarm time reached\n'
                   ~ '- sensor_context: ' ~ (sensor_context | string)
                }}
            response_variable: wake_llm
            continue_on_error: true
          - variables:
              wake_message: >
                {% set res = wake_llm | default({}) %}
                {{ res.response.speech.plain.speech | default(wake_message) }}

  - alias: "Optional mobile notification with Snooze/Stop"
    choose:
      - conditions:
          - condition: template
            value_template: >
              {{ v_notify_service | default('') | string | length > 0 }}
        sequence:
          - service: "{{ v_notify_service }}"
            data:
              title: "wake-up guard"
              message: "time to get up, miquel."
              data:
                actions:
                  - action: !input mobile_snooze_action_id
                    title: "Snooze"
                  - action: !input mobile_stop_action_id
                    title: "Stop"

  - alias: "Speak wake-up message (first round)"
    choose:
      - alias: "TTS with voice_profile"
        conditions:
          - condition: template
            value_template: >
              {{ v_voice_profile | default('') | string | length > 0 }}
        sequence:
          - service: tts.speak
            target:
              entity_id: !input tts_engine
            data:
              media_player_entity_id: !input tts_output_player
              message: "{{ wake_message }}"
              options:
                voice_profile: !input voice_profile
    default:
      - service: tts.speak
        target:
          entity_id: !input tts_engine
        data:
          media_player_entity_id: !input tts_output_player
          message: "{{ wake_message }}"

  - alias: "Wait for Snooze/Stop (first round)"
    wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: !input mobile_snooze_action_id
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: !input mobile_stop_action_id
    timeout:
      seconds: !input post_tts_timeout
    continue_on_timeout: true

  - alias: "Handle Snooze/Stop or timeout (first round)"
    choose:
      - alias: "Stop pressed in first window"
        conditions:
          - condition: template
            value_template: >
              {{ wait.trigger is not none
                 and wait.trigger.event is defined
                 and wait.trigger.event.data.action == v_mobile_stop_action_id }}
        sequence:
          - alias: "Stop TTS immediately (first window)"
            service: media_player.media_stop
            target:
              entity_id: !input tts_output_player
          - alias: "Restore volume after Stop"
            service: media_player.volume_set
            target:
              entity_id: !input tts_output_player
            data:
              volume_level: !input tts_volume_after
          - stop: "wake-up guard stopped by user (stop in first window)"

      - alias: "Snooze pressed in first window"
        conditions:
          - condition: template
            value_template: >
              {{ wait.trigger is not none
                 and wait.trigger.event is defined
                 and wait.trigger.event.data.action == v_mobile_snooze_action_id }}
        sequence:
          - alias: "Stop TTS immediately (snooze)"
            service: media_player.media_stop
            target:
              entity_id: !input tts_output_player

          - alias: "Wait for snooze period"
            delay:
              minutes: !input snooze_minutes

          - alias: "Speak wake-up message again after snooze"
            choose:
              - alias: "TTS with voice_profile"
                conditions:
                  - condition: template
                    value_template: >
                      {{ v_voice_profile | default('') | string | length > 0 }}
                sequence:
                  - service: tts.speak
                    target:
                      entity_id: !input tts_engine
                    data:
                      media_player_entity_id: !input tts_output_player
                      message: "{{ wake_message }}"
                      options:
                        voice_profile: !input voice_profile
            default:
              - service: tts.speak
                target:
                  entity_id: !input tts_engine
                data:
                  media_player_entity_id: !input tts_output_player
                  message: "{{ wake_message }}"

          - alias: "Final wait for Stop after snooze"
            wait_for_trigger:
              - platform: event
                event_type: mobile_app_notification_action
                event_data:
                  action: !input mobile_stop_action_id
            timeout:
              seconds: !input post_tts_timeout
            continue_on_timeout: true

          - alias: "Stop or play music after snooze"
            choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ wait.trigger is not none
                         and wait.trigger.event is defined
                         and wait.trigger.event.data.action == v_mobile_stop_action_id }}
                sequence:
                  - alias: "Stop TTS immediately (stop after snooze)"
                    service: media_player.media_stop
                    target:
                      entity_id: !input tts_output_player
                  - alias: "Restore volume after Stop (after snooze)"
                    service: media_player.volume_set
                    target:
                      entity_id: !input tts_output_player
                    data:
                      volume_level: !input tts_volume_after
                  - stop: "wake-up guard stopped by user (stop after snooze)"
            default:
              - alias: "No stop after snooze – start wake-up music"
                service: script.turn_on
                target:
                  entity_id: !input music_script
              - alias: "Restore volume after music (after snooze)"
                service: media_player.volume_set
                target:
                  entity_id: !input tts_output_player
                data:
                  volume_level: !input tts_volume_after
              - stop: "wake-up guard finished after snooze + music"

    default:
      - alias: "No Snooze/Stop in first window – play music"
        service: script.turn_on
        target:
          entity_id: !input music_script
      - alias: "Restore volume after music (no snooze)"
        service: media_player.volume_set
        target:
          entity_id: !input tts_output_player
        data:
          volume_level: !input tts_volume_after
      - stop: "wake-up guard finished after first message + music"
