blueprint:
  name: "Wake-up alarm – LLM context"
  author: madalone
  description: '![Wake-up alarm header](/local/blueprint-images/llm_alarm-header.jpeg)

    # Wake-up alarm – LLM context

    Time-based alarm that fires on selected weekdays, optionally generates a
    wake-up message via a conversation agent, speaks it over TTS, and supports
    one snooze cycle with mobile notification controls.

    ### Recent changes

    - **v2:** Style guide compliance — collapsible input sections, `action:` syntax,
      header fields, description image

    - **v1:** Initial version'
  domain: automation
  homeassistant:
    min_version: "2024.6.0"
  input:
    # ... (full v2 content preserved in live file at time of backup)
