blueprint:
  name: Music Assistant – Follow me (multi-room advanced)
  author: madalone
  description: >
    ![Image](https://brands.home-assistant.io/_/music_assistant/logo.png)

    # Music Assistant – Follow me (multi-room advanced)

    Presence-driven follow-me for Music Assistant queues across multiple zones.
    Transfers the active queue to whichever room you walk into, with priority
    ordering, anti-flicker, cooldown, playback protection, optional announcements,
    and a TTS duration filter to ignore short clips.

    ### Recent changes

    - **v6:** Replaced single TTS players list with independent pre-transfer
      and post-transfer TTS player lists. Each list is parallel to the
      presence sensors — you choose exactly which hardware speaker handles
      each announcement phase per zone. Added exclusive-room toggle to
      silence all non-target players after a successful transfer.

    - **v5:** Removed divert mode entirely. To route music to a fixed room,
      place the same MA player in every target_players slot. Simplified
      target_player and tts_output_player resolution (no branching).

    - **v4:** Added TTS output players list (parallel to presence sensors and
      MA players) so announcement scripts target physical hardware speakers
      instead of MA virtual players.
      Fixes TTS hang when announcing on MA player abstractions during playback.

    - **v3:** Added excluded source players blacklist and follow-paused-music
      toggle.

    - **v2:** Style guide compliance — modern syntax (`action:`, `triggers:`),
      collapsible input sections, aliases on all steps, MA integration filter,
      removed dead variables, added template safety defaults.
  domain: automation
  homeassistant:
    min_version: "2024.6.0"
