blueprint:
  name: "🚽💡 Smart Bathroom Occupancy Light Control (Door + Shower Zone Optional)"
  author: Murat Çeşmecioğlu (modified by Madalone & Miquel)
  description: >
    Optional door sensor and shower zone version.
    Enable the toggles to activate the door sensor or shower zone sensor,
    then pick them from the dropdown.
    If a toggle is off, that sensor is ignored.
    If shower_zone_sensor is enabled (e.g. an Aqara FP2 zone), the light will NOT
    turn off while that zone detects presence — even if the main motion sensor
    clears (e.g. blocked by a glass shower door).
  domain: automation

  input:
    use_door_sensor:
      name: Use Door Sensor?
      description: Enable this if you have a door/contact sensor in the bathroom.
      default: false
      selector:
        boolean: {}

    door_sensor:
      name: Door Sensor
      description: >
        The door/contact sensor entity. Only used if "Use Door Sensor?" is enabled.
      default: {}
      selector:
        entity:
          domain:
            - binary_sensor
          device_class:
            - door
            - opening
          multiple: false

    motion_sensor:
      name: Motion Sensor
      description: This motion sensor is used to confirm when someone enters the bathroom.
      selector:
        entity:
          domain:
            - binary_sensor
          multiple: false

    use_shower_zone:
      name: Use Shower Zone Sensor?
      description: Enable this if you have a dedicated presence zone covering the shower (e.g. Aqara FP2 zone).
      default: false
      selector:
        boolean: {}

    shower_zone_sensor:
      name: Shower Zone Sensor
      description: >
        The presence zone sensor covering the shower area. Only used if "Use Shower Zone Sensor?" is enabled.
      default: {}
      selector:
        entity:
          domain:
            - binary_sensor
          device_class:
            - occupancy
            - presence
            - motion
          multiple: false

    light_entity:
      name: Light
      description: Bathroom light.
      selector:
        entity:
          filter:
            - domain:
                - light
                - switch
                - input_boolean
          multiple: false

    helper_entity:
      name: Occupancy Helper
      description: This helper entity monitors room occupancy.
      selector:
        entity:
          domain:
            - input_boolean
          multiple: false

    delay_before_motion_check:
      name: Motion Sensor Delay (second)
      description: The time the motion sensor takes before clearing its detected state. (Default=2)
      default: 2
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: s
          mode: slider

mode: single

variables:
  has_door: !input use_door_sensor
  door_entity: !input door_sensor
  has_shower_zone: !input use_shower_zone
  shower_zone: !input shower_zone_sensor
  door_is_open: "{{ has_door and is_state(door_entity, 'on') }}"
  door_is_closed: "{{ has_door and is_state(door_entity, 'off') }}"
  shower_zone_active: "{{ has_shower_zone and is_state(shower_zone, 'on') }}"

trigger:
  # Door triggers (only become "active" if door is enabled)
  - platform: template
    id: door_opened
    value_template: "{{ has_door and is_state(door_entity, 'on') }}"

  - platform: template
    id: door_closed
    value_template: "{{ has_door and is_state(door_entity, 'off') }}"

  # Motion triggers
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
    id: motion_detected

  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for:
      seconds: !input delay_before_motion_check
    id: motion_stopped

  # Shower zone trigger (only active if shower zone is enabled)
  - platform: template
    id: shower_zone_cleared
    value_template: "{{ has_shower_zone and is_state(shower_zone, 'off') }}"

action:
  # 1) Motion stopped -> if (door open OR no door) and occupied
  #    AND shower zone is NOT active -> turn off
  - choose:
      - conditions:
          - condition: trigger
            id: motion_stopped
          - condition: template
            value_template: "{{ (not has_door) or door_is_open }}"
          - condition: state
            entity_id: !input helper_entity
            state: "on"
          - condition: template
            value_template: "{{ not shower_zone_active }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input light_entity
          - service: input_boolean.turn_off
            target:
              entity_id: !input helper_entity

  # 2) Door opened and not occupied -> turn on light (only if door enabled)
  - choose:
      - conditions:
          - condition: trigger
            id: door_opened
          - condition: template
            value_template: "{{ has_door }}"
          - condition: state
            entity_id: !input helper_entity
            state: "off"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input light_entity

  # 3) Motion detected and helper off -> mark occupied
  - choose:
      - conditions:
          - condition: trigger
            id: motion_detected
          - condition: state
            entity_id: !input helper_entity
            state: "off"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input helper_entity

  # 4) Motion detected -> if (door open OR no door) -> turn on light and mark occupied
  - choose:
      - conditions:
          - condition: trigger
            id: motion_detected
          - condition: template
            value_template: "{{ (not has_door) or door_is_open }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input light_entity
          - service: input_boolean.turn_on
            target:
              entity_id: !input helper_entity

  # 5) Door opened while occupied -> wait for motion to stop AND shower zone clear, then turn off
  - choose:
      - conditions:
          - condition: trigger
            id: door_opened
          - condition: template
            value_template: "{{ has_door }}"
          - condition: state
            entity_id: !input helper_entity
            state: "on"
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: !input motion_sensor
                to: "off"
                for:
                  seconds: !input delay_before_motion_check
            continue_on_timeout: false
          # After motion stops, also wait for shower zone to clear (if enabled)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ shower_zone_active }}"
                sequence:
                  - wait_for_trigger:
                      - platform: template
                        value_template: "{{ is_state(shower_zone, 'off') }}"
                    continue_on_timeout: false
          - service: homeassistant.turn_off
            target:
              entity_id: !input light_entity
          - service: input_boolean.turn_off
            target:
              entity_id: !input helper_entity

  # 6) Door closed while not occupied -> turn off light (only if door enabled)
  - choose:
      - conditions:
          - condition: trigger
            id: door_closed
          - condition: template
            value_template: "{{ has_door }}"
          - condition: state
            entity_id: !input helper_entity
            state: "off"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input light_entity

  # 7) Shower zone cleared -> if motion already off and occupied -> turn off light
  - choose:
      - conditions:
          - condition: trigger
            id: shower_zone_cleared
          - condition: state
            entity_id: !input helper_entity
            state: "on"
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
          - condition: template
            value_template: "{{ (not has_door) or door_is_open }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input light_entity
          - service: input_boolean.turn_off
            target:
              entity_id: !input helper_entity