blueprint:
  name: "Wake-Up Guard - External Alarm trigger (Android/Alexa/etc.)"
  description: >
    Triggers your wake-up script based on an external alarm time sensor,
    such as:
      - Android phone next alarm (sensor.<phone>_next_alarm)
      - Alexa Media Player next alarm (sensor.<echo>_next_alarm)
    Optionally runs some minutes BEFORE the alarm instead of exactly
    at the alarm time.

    This is designed to hook into an existing wake-up script like
    'script.wake_up_guard_rick'. That script handles all the actual
    yelling / negotiation / lights / music.

  domain: automation

  input:
    alarm_sensor:
      name: Alarm time sensor
      description: >
        Sensor that holds the next alarm time as a timestamp.
        Examples:
          - sensor.pixel_7_next_alarm
          - sensor.bedroom_echo_next_alarm
        It must be a sensor with device class "timestamp".
      selector:
        entity:
          domain: sensor
          device_class: timestamp

    offset_minutes:
      name: Offset before alarm (minutes)
      description: >
        How many minutes BEFORE the alarm time to trigger the wake-up
        script.
        Example:
          - 0 = run exactly at the alarm time
          - 10 = run 10 minutes before the alarm
      default: 0
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: min
          mode: slider

    wakeup_script:
      name: Wake-up script to run
      description: >
        Script that performs the actual wake-up routine, e.g.
        script.wake_up_guard_rick.
      selector:
        entity:
          domain: script

mode: single
max_exceeded: silent

trigger:
  # Check once per minute if it's time to run
  - platform: time_pattern
    minutes: "/1"

condition:
  - condition: template
    alias: "Check if it's time to run relative to alarm"
    value_template: >
      {% set alarm = states( !input alarm_sensor ) %}
      {% if alarm in ['unknown', 'unavailable', 'none', ''] %}
        false
      {% else %}
        {% set alarm_ts = as_timestamp(alarm) %}
        {% set now_ts = as_timestamp(now()) %}
        {% set offset = ( !input offset_minutes | int ) * 60 %}
        {% set target_ts = alarm_ts - offset %}
        {% set delta = target_ts - now_ts %}
        {# Run when target time is between now and 60s from now #}
        {{ 0 <= delta < 60 }}
      {% endif %}

action:
  - service: script.turn_on
    target:
      entity_id: !input wakeup_script
