blueprint:
  name: Agent Randomizer
  author: madalone
  description: >
    ![Image](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/agent_randomizer-header.jpeg)

    # Agent Randomizer

    Script blueprint that returns a random conversation agent + paired TTS
    entity from a configurable pool. Each conversation agent slot has a
    corresponding TTS slot — when conversation agent 3 is picked, TTS 3
    comes with it. Supports up to 10 conversation agent/TTS pairs. Empty
    slots are filtered out automatically.

    Fill any combination of slots — there is no required "primary" slot.
    The script picks randomly from whichever slots are populated.

    **Calling convention:** Invoke with `action: script.<your_instance_id>`
    and `response_variable`. Do NOT use `script.turn_on` — that is
    fire-and-forget and will not return the response.

    ```yaml
    - action: script.agent_randomizer
      response_variable: randomizer
    - action: conversation.process
      data:
        agent_id: "{{ randomizer.agent }}"
        text: "Your prompt here"
      response_variable: llm_response
    - action: tts.speak
      target:
        entity_id: "{{ randomizer.tts }}"
      data:
        media_player_entity_id: media_player.kitchen_speaker
        message: "{{ llm_response.response.speech.plain.speech }}"
    ```

    ### Returns

    | Key               | Value                                      |
    |-------------------|--------------------------------------------|
    | `result.agent`    | Selected conversation agent entity         |
    | `result.tts`      | Paired TTS entity                          |
    | `result.name`     | Display name of the selected agent         |
    | `result.roster`   | Full list of all populated pairs (for direct-address detection) |

    ### Changelog

    - **v1.2 (2026-02-27):** Alias support — name inputs accept comma-separated
      aliases (first = canonical display name, rest = detection-only);
      roster entries carry aliases for fuzzy direct-address matching

    - **v1.1 (2026-02-27):** Added display name per pair + roster return

    - **v1.0 (2026-02-27):** Initial version — 10 conversation agent/TTS
      pair slots, structured response via stop + response_variable

  domain: script
  source_url: https://github.com/mmadalone/HA-Master-Repo/blob/main/script/agent_randomizer.yaml
  homeassistant:
    min_version: "2024.10.0"

  input:
    # ── Section 1: Conversation Agent / TTS Pairs 1–5 ──────────
    pool_1_to_5:
      name: "① Conversation Agent / TTS Pairs 1–5"
      icon: mdi:account-group
      description: >
        Conversation agent and TTS pairs. Fill any slots you need —
        empty slots are excluded from the pool automatically.
      collapsed: false
      input:
        agent_1:
          name: "Conversation Agent 1"
          description: "Leave empty to exclude from pool."
          default: ""
          selector:
            conversation_agent:
        name_1:
          name: "Display Name / Aliases 1"
          description: >-
            Comma-separated names and nicknames (e.g. "Rick, Rickeee, Ricky").
            First value is the canonical display name used in prompts.
            Remaining values are detection-only aliases.
          default: ""
          selector:
            text:
              multiline: false
        tts_1:
          name: "TTS for Conversation Agent 1"
          default: ""
          selector:
            entity:
              filter:
                domain: tts
        agent_2:
          name: "Conversation Agent 2"
          description: "Leave empty to exclude from pool."
          default: ""
          selector:
            conversation_agent:
        name_2:
          name: "Display Name / Aliases 2"
          description: "Comma-separated: first = display name, rest = aliases."
          default: ""
          selector:
            text:
              multiline: false
        tts_2:
          name: "TTS for Conversation Agent 2"
          default: ""
          selector:
            entity:
              filter:
                domain: tts
        agent_3:
          name: "Conversation Agent 3"
          description: "Leave empty to exclude from pool."
          default: ""
          selector:
            conversation_agent:
        name_3:
          name: "Display Name / Aliases 3"
          description: "Comma-separated: first = display name, rest = aliases."
          default: ""
          selector:
            text:
              multiline: false
        tts_3:
          name: "TTS for Conversation Agent 3"
          default: ""
          selector:
            entity:
              filter:
                domain: tts
        agent_4:
          name: "Conversation Agent 4"
          description: "Leave empty to exclude from pool."
          default: ""
          selector:
            conversation_agent:
        name_4:
          name: "Display Name / Aliases 4"
          description: "Comma-separated: first = display name, rest = aliases."
          default: ""
          selector:
            text:
              multiline: false
        tts_4:
          name: "TTS for Conversation Agent 4"
          default: ""
          selector:
            entity:
              filter:
                domain: tts
        agent_5:
          name: "Conversation Agent 5"
          description: "Leave empty to exclude from pool."
          default: ""
          selector:
            conversation_agent:
        name_5:
          name: "Display Name / Aliases 5"
          description: "Comma-separated: first = display name, rest = aliases."
          default: ""
          selector:
            text:
              multiline: false
        tts_5:
          name: "TTS for Conversation Agent 5"
          default: ""
          selector:
            entity:
              filter:
                domain: tts

    # ── Section 2: Conversation Agent / TTS Pairs 6–10 ─────────
    pool_6_to_10:
      name: "② Conversation Agent / TTS Pairs 6–10"
      icon: mdi:account-multiple-plus
      description: >
        Extended pool for large conversation agent rosters. Leave
        agent empty to exclude that slot.
      collapsed: true
      input:
        agent_6:
          name: "Conversation Agent 6"
          description: "Leave empty to exclude from pool."
          default: ""
          selector:
            conversation_agent:
        name_6:
          name: "Display Name / Aliases 6"
          description: "Comma-separated: first = display name, rest = aliases."
          default: ""
          selector:
            text:
              multiline: false
        tts_6:
          name: "TTS for Conversation Agent 6"
          default: ""
          selector:
            entity:
              filter:
                domain: tts
        agent_7:
          name: "Conversation Agent 7"
          description: "Leave empty to exclude from pool."
          default: ""
          selector:
            conversation_agent:
        name_7:
          name: "Display Name / Aliases 7"
          description: "Comma-separated: first = display name, rest = aliases."
          default: ""
          selector:
            text:
              multiline: false
        tts_7:
          name: "TTS for Conversation Agent 7"
          default: ""
          selector:
            entity:
              filter:
                domain: tts
        agent_8:
          name: "Conversation Agent 8"
          description: "Leave empty to exclude from pool."
          default: ""
          selector:
            conversation_agent:
        name_8:
          name: "Display Name / Aliases 8"
          description: "Comma-separated: first = display name, rest = aliases."
          default: ""
          selector:
            text:
              multiline: false
        tts_8:
          name: "TTS for Conversation Agent 8"
          default: ""
          selector:
            entity:
              filter:
                domain: tts
        agent_9:
          name: "Conversation Agent 9"
          description: "Leave empty to exclude from pool."
          default: ""
          selector:
            conversation_agent:
        name_9:
          name: "Display Name / Aliases 9"
          description: "Comma-separated: first = display name, rest = aliases."
          default: ""
          selector:
            text:
              multiline: false
        tts_9:
          name: "TTS for Conversation Agent 9"
          default: ""
          selector:
            entity:
              filter:
                domain: tts
        agent_10:
          name: "Conversation Agent 10"
          description: "Leave empty to exclude from pool."
          default: ""
          selector:
            conversation_agent:
        name_10:
          name: "Display Name / Aliases 10"
          description: "Comma-separated: first = display name, rest = aliases."
          default: ""
          selector:
            text:
              multiline: false
        tts_10:
          name: "TTS for Conversation Agent 10"
          default: ""
          selector:
            entity:
              filter:
                domain: tts

sequence:
  - variables:
      _agents:
        - !input agent_1
        - !input agent_2
        - !input agent_3
        - !input agent_4
        - !input agent_5
        - !input agent_6
        - !input agent_7
        - !input agent_8
        - !input agent_9
        - !input agent_10
      _tts:
        - !input tts_1
        - !input tts_2
        - !input tts_3
        - !input tts_4
        - !input tts_5
        - !input tts_6
        - !input tts_7
        - !input tts_8
        - !input tts_9
        - !input tts_10
      _names:
        - !input name_1
        - !input name_2
        - !input name_3
        - !input name_4
        - !input name_5
        - !input name_6
        - !input name_7
        - !input name_8
        - !input name_9
        - !input name_10
      _pairs: >-
        {%- set ns = namespace(result=[]) -%}
        {%- for i in range(10) -%}
          {%- if _agents[i] != '' -%}
            {%- set raw = _names[i] | default('') | string -%}
            {%- set canonical = (raw.split(',')[0] | trim) if raw | length > 0 else '' -%}
            {%- set ns.result = ns.result + [{'agent': _agents[i], 'tts': _tts[i], 'name': canonical, 'aliases': raw}] -%}
          {%- endif -%}
        {%- endfor -%}
        {{ ns.result }}
      _picked: >-
        {%- if _pairs | length > 0 -%}
          {{ _pairs | random }}
        {%- else -%}
          {{ {'agent': '', 'tts': '', 'name': ''} }}
        {%- endif -%}
      result:
        agent: "{{ _picked.agent }}"
        tts: "{{ _picked.tts }}"
        name: "{{ _picked.name }}"
        roster: "{{ _pairs }}"
  - stop: ""
    response_variable: result
