blueprint:
  name: Announce Music Follow Me (TTS)
  description: |
    Announces, via TTS, where the music was moved for the
    "Music Assistant – Follow Me" automation.

    ✅ Features:
      - Works with any TTS entity (Piper, ElevenLabs, etc.).
      - Editable random Rick/Quark-style messages (one per list entry).
      - Optional single default message for non-random mode.
      - ElevenLabs-friendly options:
        - Official: `voice` (via options.voice).
        - Custom: `voice_profile` (via options.voice_profile).
        - If voice_profile is set, voice is NOT sent.

    🧠 Placeholders you can use in your text:
      - {player_name}   → Friendly name of the target player
      - {target_player} → Entity ID of the target player

  domain: script

  input:
    tts_entity:
      name: TTS entity
      description: >
        The TTS entity to use for announcements (e.g. ElevenLabs, Piper,
        your Rick/Quark TTS). Example: tts.elevenlabs, tts.elevenlabs_custom_tts.
      selector:
        entity:
          domain: tts

    use_random_messages:
      name: Use random fun messages
      description: >
        If enabled, the script will use a random message from the list below.
        If disabled, it will use the "Default message template".
      default: true
      selector:
        boolean: {}

    custom_random_messages:
      name: Random messages (editable list)
      description: >
        YAML list of messages. Used when "Use random fun messages" is enabled.
        Use {player_name} and/or {target_player} as placeholders.
        If you clear this list, a built-in set of Rick-style defaults is used.
      default:
        - "Rick here. Moving the music to {player_name}. Try to keep up."
        - "Quark here. I moved your music to {player_name}. Your latinum is in good hands."
        - "Music transferred to {player_name}. Don't screw this up."
        - "Yo! Your tunes are now blasting in {player_name}."
        - "Portal opened. Music jumped to {player_name}."
      selector:
        object: {}

    default_message:
      name: Default message template (non-random mode)
      description: >
        Used when "Use random fun messages" is OFF.
        Use {player_name} and/or {target_player} as placeholders.
      default: "Moving the music to {player_name}."
      selector:
        text:
          multiline: true

    elevenlabs_voice:
      name: ElevenLabs voice (optional, OFFICIAL integration only)
      description: >
        For the OFFICIAL ElevenLabs integration (tts.elevenlabs):
        Sets the `voice` option of tts.speak (voice ID or voice name).
        Ignored if a custom voice_profile is set.
      default: ""
      selector:
        text: {}

    elevenlabs_voice_profile:
      name: ElevenLabs custom voice profile (optional, CUSTOM integration)
      description: >
        For CUSTOM ElevenLabs integrations (e.g. tts.elevenlabs_custom_tts):
        Sets the `voice_profile` option of tts.speak.
        When this is set, the `voice` option is NOT sent.
      default: ""
      selector:
        text: {}

mode: queued
max_exceeded: silent

fields:
  target_player:
    name: Target player
    description: >
      Media player where the music was moved, or where to play this test
      announcement when running the script manually.
    example: media_player.workshop
    selector:
      entity:
        domain: media_player

variables:
  tts_entity_id: !input tts_entity
  random_mode: !input use_random_messages
  custom_msgs: !input custom_random_messages
  default_msg_template: !input default_message
  el_voice: !input elevenlabs_voice
  el_voice_profile: !input elevenlabs_voice_profile

sequence:
  - service: tts.speak
    target:
      entity_id: "{{ tts_entity_id }}"
    data:
      media_player_entity_id: "{{ target_player }}"
      message: >
        {{
          (
            custom_msgs
            if (random_mode | bool)
            else [default_msg_template or 'Moving the music to {player_name}.']
          )
          | default(
              [
                'Rick here. Moving the music to {player_name}. Try to keep up.',
                'Quark here. I moved your music to {player_name}. Your latinum is in good hands.',
                "Music transferred to {player_name}. Don't screw this up.",
                'Yo! Your tunes are now blasting in {player_name}.',
                'Portal opened. Music jumped to {player_name}.'
              ],
              true
            )
          | random
          | replace(
              '{player_name}',
              (state_attr(target_player, 'friendly_name') or target_player)
            )
          | replace('{target_player}', target_player)
        }}
      options:
        voice: >
          {{
            el_voice
            if (not el_voice_profile) and el_voice
            else omit
          }}
        voice_profile: >
          {{
            el_voice_profile
            if el_voice_profile
            else omit
          }}
