blueprint:
  name: bedtime media play wrapper (music assistant)
  description: >
    wrapper script to play bedtime media (especially audiobooks) via music assistant.
    it always targets the passed-in music assistant media_player (so your bedtime blueprint can pass its selected player).
  domain: script

  input:
    media_player:
      name: target player (music assistant)
      description: this is the player your bedtime blueprint selects from its menu and passes into this script.
      selector:
        entity:
          filter:
            integration: music_assistant
            domain: media_player
          multiple: false

    media_type:
      name: media type
      description: for bedtime, you’ll usually use audiobook.
      default: audiobook
      selector:
        select:
          options:
            - audiobook
            - podcast
            - radio
            - track
            - album
            - artist
            - playlist

    media_id:
      name: media id (name or uri)
      description: >
        can be a name (e.g. "bedtime stories for cynics") or a uri (e.g. "library://audiobook/86").
      selector:
        text:

    enqueue:
      name: enqueue
      description: replace starts fresh; add appends to the queue.
      default: replace
      selector:
        select:
          options:
            - replace
            - add

    volume:
      name: volume
      description: >
        playback volume (0.0 to 1.0). if set, volume is applied before playback starts.
        leave empty to keep the player's current volume.
      default: []
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider

    shuffle:
      name: shuffle
      description: set shuffle on the target player after starting playback.
      default: false
      selector:
        boolean:

mode: queued
max: 10

sequence:
  - variables:
      _player: !input media_player
      _media_type: "{{ (!input media_type) | string | trim }}"
      _media_id: "{{ (!input media_id) | string | trim }}"
      _enqueue: "{{ (!input enqueue) | string | trim }}"
      _volume: "{{ (!input volume) | default([]) }}"
      _shuffle: "{{ (!input shuffle) | default(false) }}"

      action_data: >
        {{
          dict(
            media_id=_media_id,
            media_type=_media_type,
            enqueue=_enqueue
          )
        }}

      target_data: >
        {{
          dict(entity_id=_player)
        }}

  - alias: set playback volume (optional)
    if:
      - condition: template
        value_template: "{{ _volume not in [[], none, ''] }}"
    then:
      - alias: apply volume level
        action: media_player.volume_set
        data:
          volume_level: "{{ _volume | float(0.35) }}"
        target: "{{ target_data }}"

  - alias: play media via music assistant (forced target player)
    action: music_assistant.play_media
    data: "{{ action_data }}"
    target: "{{ target_data }}"

  - alias: set shuffle (optional)
    action: media_player.shuffle_set
    data:
      shuffle: "{{ _shuffle }}"
    target: "{{ target_data }}"
