blueprint:
  name: "Bedtime Media Play Wrapper — Music Assistant"
  author: madalone
  source_url: https://github.com/mmadalone/HA-Master-Repo/
  description: >
    ![Bedtime Media Play Wrapper header](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/bedtime_media_play_wrapper-header.jpeg)

    # Bedtime Media Play Wrapper

    Wrapper script to play bedtime media (especially audiobooks) via Music Assistant.
    Always targets the passed-in MA media_player, so your bedtime blueprint can pass
    its selected player directly. Supports optional volume, shuffle, and enqueue control.

    ### Recent changes

    - **v2:** Restructured header, collapsible inputs, conditional shuffle, aliases
    - **v1:** Initial version — basic MA play_media wrapper with volume control
  domain: script
  homeassistant:
    min_version: "2024.10.0"

  input:
    # =========================================================================
    # ① PLAYBACK
    # =========================================================================
    playback:
      name: "① Playback"
      icon: mdi:book-music
      description: "Media content and target player configuration."
      input:
        media_player:
          name: "Target player (Music Assistant)"
          description: >-
            The MA media_player your bedtime blueprint selects and passes into
            this script.
          selector:
            entity:
              filter:
                integration: music_assistant
                domain: media_player
              multiple: false

        media_type:
          name: "Media type"
          description: "For bedtime, you'll usually use audiobook."
          default: audiobook
          selector:
            select:
              options:
                - audiobook
                - podcast
                - radio
                - track
                - album
                - artist
                - playlist

        media_id:
          name: "Media ID (name or URI)"
          description: >-
            Can be a name (e.g. "Bedtime Stories for Cynics") or a URI
            (e.g. "library://audiobook/86").
          selector:
            text:

        enqueue:
          name: "Enqueue"
          description: "Replace starts fresh; Add appends to the queue."
          default: replace
          selector:
            select:
              options:
                - replace
                - add

    # =========================================================================
    # ② VOLUME & BEHAVIOR
    # =========================================================================
    volume_behavior:
      name: "② Volume & behavior"
      icon: mdi:volume-medium
      description: "Optional volume and shuffle settings applied around playback."
      input:
        volume:
          name: "Volume"
          description: >-
            Playback volume (0.0–1.0). If set, volume is applied before playback
            starts. Leave empty to keep the player's current volume.
          default: []
          selector:
            number:
              min: 0.0
              max: 1.0
              step: 0.05
              mode: slider

        shuffle:
          name: "Shuffle"
          description: "Enable shuffle on the target player after starting playback."
          default: false
          selector:
            boolean:

mode: queued
max: 10

sequence:
  - alias: "Set local variables from inputs"
    variables:
      _player: !input media_player
      _media_type: "{{ (!input media_type) | string | trim }}"
      _media_id: "{{ (!input media_id) | string | trim }}"
      _enqueue: "{{ (!input enqueue) | string | trim }}"
      # Empty list [] sentinel — number selector has no native "unset" state
      _volume: "{{ (!input volume) | default([]) }}"
      _shuffle: "{{ (!input shuffle) | default(false) }}"

      action_data: >-
        {{
          dict(
            media_id=_media_id,
            media_type=_media_type,
            enqueue=_enqueue
          )
        }}

      target_data: >-
        {{ dict(entity_id=_player) }}

  - alias: "Set playback volume (optional — skipped if no volume provided)"
    if:
      - condition: template
        value_template: "{{ _volume not in [[], none, ''] }}"
    then:
      - alias: "Apply volume level before playback"
        action: media_player.volume_set
        data:
          volume_level: "{{ _volume | float(0.35) }}"
        target: "{{ target_data }}"

  - alias: "Play media via Music Assistant (forced target player)"
    action: music_assistant.play_media
    data: "{{ action_data }}"
    target: "{{ target_data }}"

  - alias: "Set shuffle (optional — only when enabled)"
    if:
      - condition: template
        value_template: "{{ _shuffle | bool(false) }}"
    then:
      - alias: "Enable shuffle on target player"
        action: media_player.shuffle_set
        data:
          shuffle: true
        target: "{{ target_data }}"
