blueprint:
  name: "Chime TTS – Simple Announce (Quark edition)"
  description: >
    ![Header](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/chime_tts_simple_announce-header.jpeg)

    v2.0 — Generic Chime TTS script blueprint. Plays a chime followed by TTS
    on selected media players via the chime_tts.say service. Use as a building
    block in automations and other blueprints — create one script per voice
    persona, then call it from anywhere.
  domain: script
  author: madalone
  source_url: https://github.com/mmadalone/HA-Master-Repo/blob/main/script/chime_tts_simple_announce.yaml
  homeassistant:
    min_version: "2024.10.0"

  input:
    # ─── ① Media Players ────────────────────────────────────────────
    section_players:
      name: "① Media Players"
      icon: mdi:speaker-group
      collapsed: false
      input:
        target_players:
          name: Target media players
          description: >
            Media players for chime + TTS output (e.g. Voice PE satellites,
            Sonos, Alexa).
          selector:
            entity:
              multiple: true
              filter:
                domain:
                  - media_player

    # ─── ② Message & TTS Settings ───────────────────────────────────
    section_message:
      name: "② Message & TTS Settings"
      icon: mdi:message-text
      collapsed: true
      input:
        message_template:
          name: Default message / template
          description: >
            Plain text or Jinja template for the spoken message.
          default: "Portal opened. Music jumped to the workshop."
          selector:
            template:

        tts_speed:
          name: TTS speed (%)
          description: >
            Playback speed for TTS. 100 = normal.
          default: 100
          selector:
            number:
              min: 50
              max: 150
              step: 5
              unit_of_measurement: "%"

    # ─── ③ Chime & Volume ───────────────────────────────────────────
    section_chime:
      name: "③ Chime & Volume"
      icon: mdi:bell-ring
      collapsed: true
      input:
        chime_path:
          name: Chime path / preset
          description: >
            Built-in chime name (e.g. "soft", "doorbell") or full path to an
            MP3 file. Leave default for the soft chime.
          default: "soft"
          selector:
            text:

        volume_level:
          name: Volume level
          description: >
            Announcement volume (0.0–1.0). Set to -1 to keep current volume.
          default: -1
          selector:
            number:
              min: -1
              max: 1
              step: 0.05

sequence:
  - alias: "Play chime + TTS — deliver announcement via Chime TTS"
    action: chime_tts.say
    target:
      entity_id: !input target_players
    data:
      message: !input message_template
      chime_path: !input chime_path
      tts_speed: !input tts_speed
      volume_level: !input volume_level
      cache: false
    continue_on_error: true

mode: queued
