blueprint:
  name: "Voice — Play bedtime audiobook (Music Assistant)"
  description: >
    ![Header](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/voice_play_bedtime_audiobook.jpeg)


    LLM tool wrapper: plays an audiobook (or other media type) via Music Assistant
    on a designated player at a configurable volume. Designed as a voice-agent
    tool script — the LLM passes title, player, and optional volume at runtime
    via fields.


    Instantiate once per use-case (e.g. one for audiobooks, one for podcasts)
    with different defaults, then register each instance as an LLM tool.
  author: madalone
  source_url: https://github.com/mmadalone/HA-Master-Repo/blob/main/script/voice_play_bedtime_audiobook.yaml
  domain: script
  icon: mdi:book-music
  homeassistant:
    min_version: "2024.10.0"

  input:
    # ── 1️⃣ Playback defaults ─────────────────────────────────
    section_defaults:
      name: "1️⃣ Playback defaults"
      icon: mdi:tune
      collapsed: true
      input:
        default_volume:
          name: Default volume
          description: >
            Fallback volume when the caller doesn't specify one (0.0–1.0).
          default: 0.35
          selector:
            number:
              min: 0.0
              max: 1.0
              step: 0.05
              mode: slider

        media_type:
          name: Media type
          description: >
            Media type sent to Music Assistant. Change to 'podcast', 'track',
            etc. if you want a non-audiobook variant of this tool.
          default: audiobook
          selector:
            select:
              options:
                - audiobook
                - podcast
                - track
                - album
                - artist
                - playlist
                - radio

        enqueue:
          name: Enqueue mode
          description: >
            'replace' clears the queue and starts fresh; 'add' appends to it.
          default: replace
          selector:
            select:
              options:
                - replace
                - add

fields:
  title:
    name: Title
    description: "Media title (or URI) to search for and play."
    required: true
    selector:
      text: {}
  player:
    name: Player
    description: "Media player entity to play on."
    required: true
    selector:
      entity:
        domain: media_player
  volume:
    name: Volume
    description: >
      Playback volume (0.0–1.0). If omitted, uses the blueprint default.
    required: false
    selector:
      number:
        min: 0.0
        max: 1.0
        step: 0.05
        mode: slider

mode: single

sequence:
  - alias: "Resolve inputs and field overrides into local variables"
    variables:
      _version: "1.1.0"
      _default_volume: !input default_volume
      _media_type: !input media_type
      _enqueue: !input enqueue
      _volume: "{{ volume | default(_default_volume) | float(_default_volume) }}"
      _player: "{{ player }}"
      _title: "{{ title }}"

  - alias: "Set playback volume"
    action: media_player.volume_set
    continue_on_error: true
    target:
      entity_id: "{{ _player }}"
    data:
      volume_level: "{{ _volume }}"

  - alias: "Play media via Music Assistant"
    action: music_assistant.play_media
    target:
      entity_id: "{{ _player }}"
    data:
      media_id: "{{ _title }}"
      media_type: "{{ _media_type }}"
      enqueue: "{{ _enqueue }}"
