blueprint:
  name: Voice – Shut Up (pause all media) (tool script)
  description: |
    ![Voice Shut Up](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/voice_shut_up.jpeg)

    SCRIPT TOOL: "Shut up" – pause ALL playing media players.

    WHAT THIS SCRIPT DOES
    ---------------------
    This script is a *tool wrapper* around the automation blueprint:

      "Voice – Active Media Controls (Kodi / MA / SpotifyPlus / Alexa / etc.)"

    That automation:
      - Has an input `candidates`: all media players you want to control.
      - Implements `command = "shut_up"`:
          • Finds all CANDIDATE players currently in state 'playing'.
          • Calls media_player.media_pause on all of them.

    This script simply triggers that automation with:

      command = "shut_up"

    From an OpenAI / LLM assistant's point of view, this script is a
    single-purpose tool:

      "Pause *everything* that is currently playing sound."


    EDITABLE PHRASES
    ----------------
    This blueprint lets you configure example phrases in the inputs below:

      - "Shutdown phrases (media-stop intent)":
          Phrases that clearly mean "stop all sound".
          Default examples include:
            • shut up
            • shut the fuck up
            • be quiet
            • stop everything
            • kill the sound
            • mute everything

      - "Conversational / insult phrases (NO media-stop intent)":
          Phrases where the user insults or yells at the assistant but
          is NOT clearly asking to stop sound.
          Default examples include:
            • shut up, you're wrong
            • shut the fuck up, Rick
            • shut up, that's not what I meant

    These lists are **for you as documentation and for your LLM prompt**:
    the Home Assistant script itself does NOT parse user phrases. The
    LLM uses your agent description to decide when to call this tool.


    HOW TO USE THIS WITH AN LLM AGENT
    ---------------------------------
    1. Configure this script from the blueprint:
         - Point it at your "Voice Active Media Controls" automation.
         - Adjust the phrase lists to match how you actually talk.

    2. Expose the resulting script (e.g. script.voice_shut_up) as a tool
       to your OpenAI agent.

    3. Take the phrases you configured here and copy them into your LLM
       agent description. Example block (adapt it to your taste):

       ---
       TOOL: script.voice_shut_up
       --------------------------------
       Purpose:
         - Hard-stop all currently playing media in the house (TV, music,
           radio, Spotify, Alexa, etc.).

       Use this tool when:
         - The user clearly wants all sound to stop, using phrases like:
           {{ shutdown_phrases | join(', ') }}
           (these come from the blueprint input "Shutdown phrases".)

         - Or when they combine insults with clear audio context, e.g.:
           "shut the fuck up, the TV is too loud",
           "shut up, the music is annoying".

       Do NOT use this tool when:
         - The user is just insulting you in a purely conversational way
           without mentioning sound, noise, TV, music, radio, speakers,
           etc. For example:
           {{ conversational_phrases | join(', ') }}
           (from "Conversational / insult phrases".)
       ---

    You can tweak the lists in the blueprint UI and keep your LLM prompt
    in sync.


    REQUIREMENTS
    ------------
    You MUST already have:

      1. Created an automation from the automation blueprint:
           "Voice – Active Media Controls (Kodi / MA / SpotifyPlus / Alexa / etc.)"

      2. Configured its "candidates" input with ALL media players that
         should respond to a "shut up" command.

    This script only triggers that automation with `command = "shut_up"`.
    It checks that the automation is present and enabled, and can warn
    via persistent notifications if misconfigured.


    COMPANION SCRIPTS
    -----------------
    This script is designed to be used together with:

      - "Voice – Pause Active Media (tool script)" → `command = "pause_active"`
      - "Voice – Stop Radio (Music Assistant) (tool script)" → `command = "stop_radio"`

  domain: script
  author: Madalone + Assistant
  source_url: https://github.com/mmadalone/HA-Master-Repo/blob/main/script/voice_shut_up.yaml

  input:
    section_core:
      name: "① Core Configuration"
      icon: mdi:cog
      collapsed: false
      input:
        active_media_automation:
          name: "Voice Active Media Controls automation"
          description: |
            Select the automation created from the automation blueprint:
              "Voice – Active Media Controls (Kodi / MA / SpotifyPlus / Alexa / etc.)"

            That automation must have its "candidates" list populated with ALL
            media players you want the "shut up" behavior to affect.
          default: ""
          selector:
            entity:
              domain: automation

        enable_notifications:
          name: Enable requirement notifications
          description: |
            When enabled, this script will create a persistent notification if:
              - The selected "Voice Active Media Controls" automation is missing
                or disabled.
          default: true
          selector:
            boolean: {}

    section_phrases:
      name: "② Phrase Documentation"
      icon: mdi:comment-text-outline
      collapsed: true
      input:
        shutdown_phrases:
          name: Shutdown phrases (media-stop intent)
          description: |
            Example phrases that *do* mean "stop all media / sound". These are
            not used by the script itself, but are meant for you to copy into
            your LLM agent description.

            Add any variations you actually use when you want the audio to stop,
            including explicit ones like:
              - "shut the fuck up"
          default:
            - shut up
            - shut the fuck up
            - be quiet
            - stop everything
            - kill the sound
            - stop all the noise
            - mute everything
          selector:
            text:
              multiline: false
              multiple: true

        conversational_phrases:
          name: Conversational / insult phrases (NO media-stop intent)
          description: |
            Example phrases where you're telling it to shut up in a more
            conversational or insulting way, *without* clearly asking media to
            stop. These are also for your LLM agent description, to show it what
            NOT to treat as a media command.

            Examples:
              - "shut up, you're wrong"
              - "shut the fuck up, Rick"
              - "shut up, that's not what I meant"
          default:
            - shut up, you're wrong
            - shut the fuck up, Rick
            - shut up, that's not what I meant
          selector:
            text:
              multiline: false
              multiple: true

mode: single
max_exceeded: silent

variables:
  active_media_automation: !input active_media_automation
  enable_notifications: !input enable_notifications
  shutdown_phrases: !input shutdown_phrases
  conversational_phrases: !input conversational_phrases

sequence:
  # 1) Requirement checks: ensure the central automation is available.
  - alias: "Resolve automation state — check if available and enabled"
    variables:
      auto_state: "{{ states(active_media_automation) | default('unavailable') }}"
      missing_or_disabled: >
        {{ auto_state in ['unavailable', 'unknown'] or auto_state == 'off' }}

  - alias: "Gate — abort if automation is missing or disabled"
    if:
      - condition: template
        value_template: "{{ missing_or_disabled }}"
    then:
      - alias: "Gate — notify only if notifications are enabled"
        if:
          - condition: template
            value_template: "{{ enable_notifications }}"
        then:
          - alias: "Warn user — automation misconfigured"
            action: persistent_notification.create
            continue_on_error: true
            data:
              title: "Voice – Shut Up (script) – Misconfiguration"
              message: >-
                The script "Voice – Shut Up" tried to run, but the selected
                "Voice Active Media Controls" automation
                ({{ active_media_automation }}) is missing, unavailable,
                or disabled.

                Please ensure you:
                  1) Created the automation from its blueprint:
                     "Voice – Active Media Controls (Kodi / MA / SpotifyPlus / Alexa / etc.)"
                  2) Enabled it.
                  3) Configured the "candidates" input with all media players
                     that should be paused for a "shut up" command.
      - alias: "Abort — automation not available"
        stop: "Active media automation not available"

  # 2) Trigger the central automation with command = "shut_up"
  - alias: "Fire shut_up command — pause all playing media via central automation"
    action: automation.trigger
    target:
      entity_id: "{{ active_media_automation }}"
    data:
      skip_condition: true
      variables:
        command: "shut_up"
