blueprint:
  name: Wake-up chime
  description: |
    ![Header](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/wakeup_chime-header.jpeg)
    Plays a simple chime sound on a media_player before it starts yelling.
    v1.1.0 — Style guide compliance pass (AP-06, BP-1, VER-2).

  domain: script
  author: madalone
  source_url: https://github.com/mmadalone/HA-Master-Repo/blob/main/script/wakeup_chime.yaml

  homeassistant:
    min_version: "2024.10.0"

  input:
    section_chime_settings:
      name: "① Chime settings"
      icon: mdi:bell-ring
      collapsed: true
      input:
        player:
          name: Chime media_player
          description: >
            Media player that should play the chime.
          selector:
            entity:
              domain: media_player

        media_id:
          name: Chime media URL or path
          description: >
            Example: /local/sounds/chime.mp3
          default: "/local/sounds/chime.mp3"
          selector:
            text: {}

        media_type:
          name: Chime media type
          description: >
            Example: music, sound, audio/mp3.
          default: "music"
          selector:
            text: {}

sequence:
  - alias: "Play chime sound on target player"
    action: media_player.play_media
    target:
      entity_id: !input player
    data:
      media_content_id: !input media_id
      media_content_type: !input media_type
    continue_on_error: true

mode: single
