blueprint:
  name: Wake-up music – Alexa
  description: |
    Plays wake-up music on an Alexa device using alexa_devices.send_text_command.

    Typical use:
    - Set volume (e.g. "set volume to 10")
    - Start a song/playlist (e.g. "play Mark on the bus by the Beastie Boys")

  domain: script

  input:
    alexa_device:
      name: Alexa device
      description: Alexa/Echo device to control.
      selector:
        device:
          integration: alexa_devices

    volume_command:
      name: Volume command
      description: >
        Text command to set volume.
        Example: "set volume to 10".
      default: "set volume to 10"
      selector:
        text: {}

    song_command:
      name: Song/playlist command
      description: >
        Text command to start music.
        Example: "play Mark on the bus by the Beastie Boys".
      default: "play Mark on the bus by the Beastie Boys"
      selector:
        text: {}

sequence:
  - service: alexa_devices.send_text_command
    data:
      device_id: !input alexa_device
      text_command: !input volume_command

  - service: alexa_devices.send_text_command
    data:
      device_id: !input alexa_device
      text_command: !input song_command

mode: single
