blueprint:
  name: Wake-up music – SpotifyPlus
  description: |
    Plays a specific track/playlist via SpotifyPlus using
    spotifyplus.player_media_play_tracks.

    IMPORTANT:
    - entity_id MUST be a SpotifyPlus media_player entity
      (e.g. media_player.spotifyplus_miquel_angel_madalone),
      NOT media_player.workshop or another MA/TV player.

    Example call this generates:
      service: spotifyplus.player_media_play_tracks
      data:
        entity_id: media_player.spotifyplus_miquel_angel_madalone
        device_id: 4fbbc98a2dc8a070fcd028bba50cf48e5fc386ee
        uris: https://open.spotify.com/track/5GdtONCuJl9N5kkzioFFUY?si=...

  domain: script

  input:
    spotifyplus_player:
      name: SpotifyPlus media_player
      description: >
        SpotifyPlus media_player entity, e.g.
        media_player.spotifyplus_miquel_angel_madalone.
        Do NOT choose media_player.workshop here.
      selector:
        entity:
          domain: media_player

    device_id:
      name: Spotify device ID
      description: >
        Spotify Connect device_id (e.g. your workshop speaker id from SpotifyPlus).
        Example: 4fbbc98a2dc8a070fcd028bba50cf48e5fc386ee
      default: ""
      selector:
        text: {}

    uris:
      name: Track/playlist URL or URI
      description: >
        Spotify URL or URI for the track/playlist to play.
        Example:
          https://open.spotify.com/track/5GdtONCuJl9N5kkzioFFUY?si=...
      default: ""
      selector:
        text: {}

sequence:
  - alias: "SpotifyPlus: play track(s)"
    service: spotifyplus.player_media_play_tracks
    data:
      entity_id: !input spotifyplus_player
      device_id: !input device_id
      uris: !input uris

mode: single
