blueprint:
  name: "Wake-up music – Music Assistant (simple)"
  author: madalone
  source_url: https://github.com/mmadalone/HA-Master-Repo/
  description: >
    ![Wake-up music MA header](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/wakeup_music_ma-header.jpeg)

    # Wake-up music – Music Assistant (simple)

    Simple helper script: set volume, clear queue, play one item on a Music
    Assistant player. Supports configurable enqueue mode and radio mode for
    continuous playback. No AFTER logic — handle post-playback with a
    separate automation if needed.

    ### Recent changes

    - **v2:** Full rebuild — music_assistant.play_media, modern syntax,
    collapsible sections, radio_mode/enqueue inputs, MA entity filter

    - **v1:** Initial version (used generic media_player.play_media)

  domain: script
  homeassistant:
    min_version: "2024.10.0"

  input:
    # ===========================================================================
    # ① PLAYER & MEDIA
    # ===========================================================================
    player_media:
      name: "① Player & media"
      icon: mdi:music-box
      description: Select the MA player and the media to play.
      input:
        player:
          name: Music Assistant player
          description: >-
            The Music Assistant speaker to play on. Only MA players are
            shown — do not use the underlying platform entity (Alexa,
            ESPHome, Sonos, etc.).
          selector:
            entity:
              filter:
                - integration: music_assistant
                  domain:
                    - media_player

        media_id:
          name: Media ID (URI or name)
          description: >-
            Music Assistant media identifier. Can be a URI
            (spotify://track/...), a library name ("Radio Klara"),
            or any string MA can resolve.
          default: ""
          selector:
            text: {}

        media_type:
          name: Media type
          description: >-
            The type of media being played. Must match the media_id
            format — e.g. "track" for a single song, "playlist" for
            a playlist, "radio" for a radio station.
          default: music
          selector:
            select:
              options:
                - label: "Music (generic)"
                  value: music
                - label: "Track"
                  value: track
                - label: "Album"
                  value: album
                - label: "Artist"
                  value: artist
                - label: "Playlist"
                  value: playlist
                - label: "Radio"
                  value: radio

    # ===========================================================================
    # ② PLAYBACK SETTINGS
    # ===========================================================================
    playback_settings:
      name: "② Playback settings"
      icon: mdi:tune-vertical
      description: Volume, queue behavior, and continuous playback options.
      input:
        volume_before:
          name: Volume BEFORE playback
          description: >-
            Set volume to this level before playing. 0.0–1.0 (1.0 = 100%).
          default: 0.6
          selector:
            number:
              min: 0
              max: 1
              step: 0.05
              mode: slider

        enqueue_mode:
          name: Enqueue mode
          description: >-
            How to handle the MA queue when playing. "replace" clears the
            queue and plays immediately (typical for wake-up). "play" plays
            immediately but keeps the rest of the queue.
          default: replace
          selector:
            select:
              options:
                - label: "Replace — clear queue, play now"
                  value: replace
                - label: "Play — play now, keep queue"
                  value: play
                - label: "Next — insert after current track"
                  value: next
                - label: "Add — append to end of queue"
                  value: add

        radio_mode:
          name: Radio mode (continuous playback)
          description: >-
            When enabled, Music Assistant keeps adding similar tracks
            when the queue ends — music never stops. Depends on the
            provider's ability to generate recommendations.
          default: "Use player settings"
          selector:
            select:
              options:
                - label: "Use player settings"
                  value: "Use player settings"
                - label: "Always"
                  value: "Always"
                - label: "Never"
                  value: "Never"

variables:
  radio_mode_value: !input radio_mode

mode: single

sequence:
  - alias: "Set volume BEFORE playback"
    action: media_player.volume_set
    target:
      entity_id: !input player
    data:
      volume_level: !input volume_before

  - alias: "Clear queue — fresh start for wake-up (non-critical, safe to fail)"
    continue_on_error: true
    action: media_player.clear_playlist
    target:
      entity_id: !input player

  - alias: "Play requested media via Music Assistant with radio mode preference"
    choose:
      - alias: "Radio mode: Always — force continuous playback"
        conditions:
          - condition: template
            value_template: "{{ radio_mode_value == 'Always' }}"
        sequence:
          - alias: "Play media with radio_mode on"
            action: music_assistant.play_media
            target:
              entity_id: !input player
            data:
              media_id: !input media_id
              media_type: !input media_type
              enqueue: !input enqueue_mode
              radio_mode: true

      - alias: "Radio mode: Never — disable continuous playback"
        conditions:
          - condition: template
            value_template: "{{ radio_mode_value == 'Never' }}"
        sequence:
          - alias: "Play media with radio_mode off"
            action: music_assistant.play_media
            target:
              entity_id: !input player
            data:
              media_id: !input media_id
              media_type: !input media_type
              enqueue: !input enqueue_mode
              radio_mode: false

    default:
      - alias: "Play media with player's default radio mode setting"
        action: music_assistant.play_media
        target:
          entity_id: !input player
        data:
          media_id: !input media_id
          media_type: !input media_type
          enqueue: !input enqueue_mode
