blueprint:
  domain: automation
  name: "Alexa ↔ Music Assistant Volume Sync"
  author: madalone
  description: |
    ![Image](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/alexa_ma_volume_sync_blueprint-header.jpeg)

    # Sync volume between Alexa devices and Music Assistant speakers

    Keeps the volume of paired Alexa Echo devices and Music Assistant
    speakers in sync — bidirectionally. Change the volume on either
    device and its partner follows. Supports mute sync too.

    ### How it works

    ```
    Echo volume/mute changes → paired MA speaker updates to match
    MA speaker volume/mute changes → paired Echo updates to match
    ```

    **Paired mode** (default): Pair multiple Echo ↔ MA speaker combos
    in one blueprint instance. Select Alexa players and MA players in
    the same order — first Alexa pairs with first MA player, second
    with second, etc.

    **Group mode**: One ring rules them all — any device's volume
    change syncs to ALL other devices in both lists. No pairing needed,
    just add all your speakers.

    ### Setup

    1. Select your **Alexa media players** (e.g. living room Echo,
       workshop Echo, bathroom Echo)
    2. Select your **Music Assistant players** in the **same order**
       (paired mode) or any order (group mode)
    3. Choose **Paired** or **Group** sync mode
    4. Optionally configure ESP boot protection if using Voice PE
       satellites
    5. Done — one instance handles all your speakers

    ### Requirements

    * **Alexa Media Player** integration must be installed
    * **Music Assistant** integration must be installed

  homeassistant:
    min_version: 2024.10.0

  input:
    # ===========================================================================
    # ① DEVICE PAIRS
    # ===========================================================================
    device_pairs:
      name: "① Device pairing"
      icon: mdi:volume-high
      collapsed: false
      description: >
        Select Alexa Echo devices and Music Assistant speakers to keep
        in volume sync. In **Paired mode**, order matters — first Alexa
        pairs with first MA player, second with second, etc. In **Group
        mode**, order does not matter — all devices sync together.
      input:
        alexa_players:
          name: Alexa media players
          default: []
          description: >
            The Alexa Echo devices exposed via the Alexa Media Player
            integration. In paired mode, order must match the MA players
            list below.
          selector:
            entity:
              filter:
                - integration: alexa_media
                  domain:
                    - media_player
              multiple: true

        ma_players:
          name: Music Assistant players (same order as Alexa players)
          default: []
          description: >
            The Music Assistant speakers to sync volume with.
            In paired mode, first MA player pairs with first Alexa
            player, etc. In group mode, order does not matter.


            **Paired mode: the order must exactly match the Alexa
            players list.**
          selector:
            entity:
              filter:
                - integration: music_assistant
                  domain:
                    - media_player
              multiple: true

    # ===========================================================================
    # ② SYNC SETTINGS
    # ===========================================================================
    sync_settings:
      name: "② Sync settings"
      icon: mdi:tune-vertical
      description: >
        Fine-tune the volume sync behaviour.
      collapsed: true
      input:
        sync_mode:
          name: Sync mode
          description: >
            **Paired** — First Alexa syncs with first MA player, second
            with second, etc. Each pair is independent.

            **Group** — One ring rules them all. Any device's volume
            change syncs to every other device in both lists.
          selector:
            select:
              options:
                - label: "Paired (1:1 matching by list order)"
                  value: paired
                - label: "Group (all devices sync together)"
                  value: group
              multiple: false
              custom_value: false
              sort: false
          default: paired

        ducking_flag:
          name: Voice PE ducking flag (input_boolean)
          description: >
            The same input_boolean used in the Voice PE duck/restore
            blueprints. When this flag is ON, volume sync is paused to
            prevent feedback loops during voice interactions. Create one
            if you don't have it yet. **Required** — select an
            input_boolean or create one before saving.
          default: ""
          selector:
            entity:
              domain: input_boolean

        sync_direction:
          name: Sync direction
          description: >
            **Both ways** — Changes on either device sync to the other.

            **Alexa → MA only** — Only Alexa volume changes update the
            MA speaker.

            **MA → Alexa only** — Only MA speaker volume changes update
            the Alexa device.
          selector:
            select:
              options:
                - label: "Both ways (recommended)"
                  value: both
                - label: "Alexa → MA speaker only"
                  value: alexa_to_ma
                - label: "MA speaker → Alexa only"
                  value: ma_to_alexa
              multiple: false
              custom_value: false
              sort: false
          default: both

        volume_tolerance:
          name: Volume tolerance (%)
          description: >
            Minimum volume difference (in percentage points) before a
            sync is triggered. Prevents unnecessary updates from small
            rounding differences between devices. Default 3% works well
            for most setups.
          default: 3
          selector:
            number:
              min: 1
              max: 15
              step: 1
              unit_of_measurement: "%"
              mode: slider

        sync_cooldown:
          name: Sync cooldown (seconds)
          description: >
            Minimum time between syncs. Adds a short delay to absorb
            rapid volume changes (e.g. holding the volume button). Also
            helps prevent feedback loops on slower devices.
          default: 1
          selector:
            number:
              min: 0
              max: 10
              step: 0.5
              unit_of_measurement: s
              mode: slider

        only_sync_when_playing:
          name: Only sync when a device is playing
          description: >
            If enabled, volume sync only occurs when at least one of the
            two paired devices is actively playing. Prevents unexpected
            volume changes when devices are idle.
          default: false
          selector:
            boolean: {}

    # ===========================================================================
    # ③ ESP BOOT PROTECTION
    # ===========================================================================
    esp_boot_protection:
      name: "③ ESP boot protection"
      icon: mdi:shield-refresh
      description: >
        Optional guards for ESPHome Voice PE satellites. Prevents
        phantom volume sync when a device boots with its physical mute
        switch engaged (which reports volume 0 to Home Assistant).
      collapsed: true
      input:
        esp_mute_switches:
          name: ESP physical mute switches (same order as MA players)
          description: >
            The hardware mute switch entities exposed by ESPHome for
            each Voice PE satellite. Must be in the **same order** as
            the MA players list above. When a mute switch is ON, volume
            changes from that device are ignored.


            Leave empty if you don't use Voice PE satellites.
          default: []
          selector:
            entity:
              filter:
                - domain: switch
              multiple: true

        boot_protection_seconds:
          name: Boot protection window (seconds)
          description: >
            After a device transitions from unavailable, ignore
            zero-volume reports for this many seconds. Prevents a
            freshly booted device (with mute switch on) from zeroing
            out all other speakers. Set to 0 to disable.
          default: 60
          selector:
            number:
              min: 0
              max: 300
              step: 10
              unit_of_measurement: s
              mode: slider

# =============================================================================
# TRIGGERS
# =============================================================================
triggers:
  - alias: "Alexa volume changed"
    trigger: state
    entity_id: !input alexa_players
    attribute: volume_level
    id: alexa_vol_changed

  - alias: "MA speaker volume changed"
    trigger: state
    entity_id: !input ma_players
    attribute: volume_level
    id: ma_vol_changed

  - alias: "Alexa mute changed"
    trigger: state
    entity_id: !input alexa_players
    attribute: is_volume_muted
    id: alexa_mute_changed

  - alias: "MA speaker mute changed"
    trigger: state
    entity_id: !input ma_players
    attribute: is_volume_muted
    id: ma_mute_changed

# =============================================================================
# VARIABLES
# =============================================================================
variables:
  alexa_list: !input alexa_players
  ma_list: !input ma_players
  ducking_flag_entity: !input ducking_flag
  direction: !input sync_direction
  tolerance: !input volume_tolerance
  cooldown: !input sync_cooldown
  only_playing: !input only_sync_when_playing
  sync_mode: !input sync_mode
  mute_switches: !input esp_mute_switches
  boot_seconds: !input boot_protection_seconds

  # Which trigger fired
  source: "{{ trigger.id }}"
  changed_entity: "{{ trigger.entity_id }}"
  is_volume_trigger: "{{ source in ['alexa_vol_changed', 'ma_vol_changed'] }}"
  is_mute_trigger: "{{ source in ['alexa_mute_changed', 'ma_mute_changed'] }}"
  is_alexa_source: "{{ source in ['alexa_vol_changed', 'alexa_mute_changed'] }}"

  # Find the pair index (used for paired mode targeting + mute switch lookup)
  pair_index: >
    {% if is_alexa_source %}
      {% set idx = alexa_list.index(changed_entity) if changed_entity in alexa_list else -1 %}
    {% else %}
      {% set idx = ma_list.index(changed_entity) if changed_entity in ma_list else -1 %}
    {% endif %}
    {{ idx }}

  # Source entity
  source_entity: "{{ changed_entity }}"

  # Paired-mode partner entity
  target_entity: >
    {% set idx = pair_index | int(-1) %}
    {% if idx >= 0 %}
      {% if is_alexa_source %}
        {{ ma_list[idx] }}
      {% else %}
        {{ alexa_list[idx] }}
      {% endif %}
    {% else %}
      {{ '' }}
    {% endif %}

  # All target entities — depends on sync mode
  all_targets: >
    {% set mode = sync_mode | default('paired') %}
    {% if mode == 'group' %}
      {{ (alexa_list + ma_list) | reject('eq', changed_entity) | list }}
    {% else %}
      {% set te = target_entity | default('') | trim %}
      {{ [te] if te != '' else [] }}
    {% endif %}

  # Current volume levels for the source
  source_vol: "{{ state_attr(source_entity, 'volume_level') | float(0) }}"

  # Current mute states
  source_muted: "{{ state_attr(source_entity, 'is_volume_muted') | default(false) }}"

  # Volume difference — in group mode, compare against first target
  target_vol: >
    {% if all_targets | length > 0 %}
      {{ state_attr(all_targets[0], 'volume_level') | float(0) }}
    {% else %}
      {{ 0 }}
    {% endif %}

  target_muted: >
    {% if all_targets | length > 0 %}
      {{ state_attr(all_targets[0], 'is_volume_muted') | default(false) }}
    {% else %}
      {{ false }}
    {% endif %}

  vol_diff: "{{ ((source_vol - target_vol) | abs * 100) | round(1) }}"

  # Direction checks
  alexa_to_ma_allowed: "{{ direction in ['both', 'alexa_to_ma'] }}"
  ma_to_alexa_allowed: "{{ direction in ['both', 'ma_to_alexa'] }}"
  direction_allowed: >
    {% if is_alexa_source %}
      {{ alexa_to_ma_allowed }}
    {% else %}
      {{ ma_to_alexa_allowed }}
    {% endif %}

  # ESP mute switch state for source device (MA-side only)
  source_mute_switch_on: >
    {% set ms = mute_switches | default([]) %}
    {% if not is_alexa_source and ms | length > 0 %}
      {% set idx = pair_index | int(-1) %}
      {% if idx >= 0 and idx < ms | length %}
        {{ states(ms[idx]) | default('off') == 'on' }}
      {% else %}
        {{ false }}
      {% endif %}
    {% else %}
      {{ false }}
    {% endif %}

  # Boot detection — was the source device recently unavailable?
  source_was_unavailable: >
    {{ trigger.from_state.state | default('') in ['unavailable', 'unknown'] }}

# =============================================================================
# ACTIONS
# =============================================================================
actions:
  # 0) Bail if no valid targets
  - condition: template
    alias: "Valid target(s) found"
    value_template: "{{ all_targets | length > 0 }}"

  # 0a) Anti-feedback loop — skip if this state change was caused by
  #     our own sync action (HA sets context.parent_id on automation-
  #     triggered state changes; physical/external changes have none)
  - condition: template
    alias: "Not a self-triggered change (anti-feedback loop)"
    value_template: >-
      {{ trigger.to_state.context.parent_id is none }}

  # 0b) Skip sync if source device is unavailable/unknown
  - condition: template
    alias: "Source device is available"
    value_template: >-
      {{ states(source_entity) | default('unavailable')
         not in ['unavailable', 'unknown'] }}

  # 1) Skip sync while Voice PE is ducking volumes
  - condition: template
    alias: "Voice PE ducking not active"
    value_template: "{{ states(ducking_flag_entity) | default('off') != 'on' }}"

  # 2) Check direction is allowed
  - condition: template
    alias: "Sync direction allowed"
    value_template: "{{ direction_allowed }}"

  # 3) ESP mute switch guard — skip if hardware mute is engaged
  - condition: template
    alias: "ESP mute switch not engaged"
    value_template: "{{ not source_mute_switch_on }}"

  # 4) Boot protection — skip zero-volume from freshly booted device
  - condition: template
    alias: "Boot protection — skip zero-volume after reboot"
    value_template: >
      {% if source_vol == 0 and boot_seconds | int(0) > 0
         and source_was_unavailable %}
        false
      {% else %}
        true
      {% endif %}

  # 5) Optional: only sync when playing
  - condition: template
    alias: "At least one device is playing (optional)"
    value_template: >
      {% if not only_playing %}
        true
      {% else %}
        {{ states(source_entity) | default('off') == 'playing'
           or (all_targets | length > 0
               and states(all_targets[0]) | default('off') == 'playing') }}
      {% endif %}

  # 6) Branch: mute sync vs volume sync
  - alias: "Route by trigger type — mute sync vs volume sync"
    choose:
      # === MUTE SYNC ===
      - alias: "Mute trigger — sync mute state to all targets"
        conditions:
          - condition: template
            value_template: "{{ is_mute_trigger }}"
        sequence:
          # Skip if mute states already match (check first target)
          - condition: template
            alias: "Mute states differ"
            value_template: "{{ source_muted != target_muted }}"
          - alias: "Sync mute state to target device(s)"
            action: media_player.volume_mute
            continue_on_error: true
            target:
              entity_id: "{{ all_targets }}"
            data:
              is_volume_muted: "{{ source_muted }}"

    # === VOLUME SYNC (default) ===
    default:
      # Skip if difference is within tolerance
      - condition: template
        alias: "Volume difference exceeds tolerance"
        value_template: >
          {{ vol_diff >= tolerance | float(3) }}

      # Cooldown delay to absorb rapid changes
      - alias: "Cooldown — absorb rapid volume changes"
        delay:
          seconds: "{{ cooldown | float(1) }}"

      # Re-read source volume after cooldown
      - alias: "Re-read source volume after cooldown"
        variables:
          fresh_source_vol: "{{ state_attr(source_entity, 'volume_level') | float(0) }}"

      # Sync mute state (vol=0 → mute, vol>0 → unmute)
      - alias: "Sync mute state — mute if volume is zero"
        action: media_player.volume_mute
        continue_on_error: true
        target:
          entity_id: "{{ all_targets }}"
        data:
          is_volume_muted: "{{ fresh_source_vol == 0 }}"

      # Sync volume level
      - alias: "Sync volume level to target device(s)"
        action: media_player.volume_set
        continue_on_error: true
        target:
          entity_id: "{{ all_targets }}"
        data:
          volume_level: "{{ fresh_source_vol }}"

mode: queued
max: 4
max_exceeded: silent
