blueprint:
  domain: automation
  name: "Alexa ↔ Music Assistant Volume Sync"
  author: madalone
  description: |
    ![Image](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/alexa_ma_volume_sync_blueprint-header.jpeg)

    # Sync volume between Alexa devices and Music Assistant speakers

    Keeps the volume of paired Alexa Echo devices and Music Assistant
    speakers in sync — bidirectionally. Change the volume on either
    device and its partner follows. Supports mute sync too.

    ### How it works

    ```
    Echo volume/mute changes → paired MA speaker updates to match
    MA speaker volume/mute changes → paired Echo updates to match
    ```

    Pair multiple Echo ↔ MA speaker combos in one blueprint instance.
    Select Alexa players and MA players in the same order — first Alexa
    pairs with first MA player, second with second, etc.

    ### Setup

    1. Select your **Alexa media players** (e.g. living room Echo,
       workshop Echo, bathroom Echo)
    2. Select your **Music Assistant players** in the **same order**
    3. Done — one instance handles all pairs

    ### Requirements

    * **Alexa Media Player** integration must be installed
    * **Music Assistant** integration must be installed

    ### Recent changes
    - **v5:** Fixed AP-44 — added `default: []` to `alexa_players` and
      `ma_players` entity inputs in Section ① for collapsed section stability.
      Added unavailability guard to prevent phantom sync-to-zero when a
      device goes unavailable or unknown.
    - **v4:** Fixed AP-16 — added `| default()` guards to all `states()` calls
      in ducking flag and playing-state conditions. Fixed AP-09a — added
      `default:` to ducking flag input for collapsed section stability.
    - **v3:** Fixed section naming convention, moved ducking flag into section
    - **v2:** Added author, header image, changelog, missing action aliases
    - **v1:** Initial version

  homeassistant:
    min_version: 2024.10.0

  input:
    # ===========================================================================
    # ① DEVICE PAIRS
    # ===========================================================================
    device_pairs:
      name: "① Device pairing"
      icon: mdi:volume-high
      collapsed: false
      description: >
        Select Alexa Echo devices and Music Assistant speakers to keep
        in volume sync. **Order matters** — first Alexa pairs with
        first MA player, second with second, etc.
      input:
        alexa_players:
          name: Alexa media players
          default: []
          description: >
            The Alexa Echo devices exposed via the Alexa Media Player
            integration. Order must match the MA players list below.
          selector:
            entity:
              filter:
                - integration: alexa_media
                  domain:
                    - media_player
              multiple: true

        ma_players:
          name: Music Assistant players (same order as Alexa players)
          default: []
          description: >
            The Music Assistant speakers to sync volume with.
            First MA player pairs with first Alexa player, etc.


            **The order must exactly match the Alexa players list.**
          selector:
            entity:
              filter:
                - integration: music_assistant
                  domain:
                    - media_player
              multiple: true

    # ===========================================================================
    # ② SYNC SETTINGS
    # ===========================================================================
    sync_settings:
      name: "② Sync settings"
      icon: mdi:tune-vertical
      description: >
        Fine-tune the volume sync behaviour.
      collapsed: true
      input:
        ducking_flag:
          name: Voice PE ducking flag (input_boolean)
          description: >
            The same input_boolean used in the Voice PE duck/restore
            blueprints. When this flag is ON, volume sync is paused to
            prevent feedback loops during voice interactions. Create one
            if you don't have it yet. **Required** — select an
            input_boolean or create one before saving.
          default: ""
          selector:
            entity:
              domain: input_boolean

        sync_direction:
          name: Sync direction
          description: >
            **Both ways** — Changes on either device sync to the other.

            **Alexa → MA only** — Only Alexa volume changes update the
            MA speaker.

            **MA → Alexa only** — Only MA speaker volume changes update
            the Alexa device.
          selector:
            select:
              options:
                - label: "Both ways (recommended)"
                  value: both
                - label: "Alexa → MA speaker only"
                  value: alexa_to_ma
                - label: "MA speaker → Alexa only"
                  value: ma_to_alexa
              multiple: false
              custom_value: false
              sort: false
          default: both

        volume_tolerance:
          name: Volume tolerance (%)
          description: >
            Minimum volume difference (in percentage points) before a
            sync is triggered. Prevents unnecessary updates from small
            rounding differences between devices. Default 3% works well
            for most setups.
          default: 3
          selector:
            number:
              min: 1
              max: 15
              step: 1
              unit_of_measurement: "%"
              mode: slider

        sync_cooldown:
          name: Sync cooldown (seconds)
          description: >
            Minimum time between syncs. Adds a short delay to absorb
            rapid volume changes (e.g. holding the volume button). Also
            helps prevent feedback loops on slower devices.
          default: 1
          selector:
            number:
              min: 0
              max: 10
              step: 0.5
              unit_of_measurement: s
              mode: slider

        only_sync_when_playing:
          name: Only sync when a device is playing
          description: >
            If enabled, volume sync only occurs when at least one of the
            two paired devices is actively playing. Prevents unexpected
            volume changes when devices are idle.
          default: false
          selector:
            boolean: {}

# =============================================================================
# TRIGGERS
# =============================================================================
triggers:
  - alias: "Alexa volume changed"
    trigger: state
    entity_id: !input alexa_players
    attribute: volume_level
    id: alexa_vol_changed

  - alias: "MA speaker volume changed"
    trigger: state
    entity_id: !input ma_players
    attribute: volume_level
    id: ma_vol_changed

  - alias: "Alexa mute changed"
    trigger: state
    entity_id: !input alexa_players
    attribute: is_volume_muted
    id: alexa_mute_changed

  - alias: "MA speaker mute changed"
    trigger: state
    entity_id: !input ma_players
    attribute: is_volume_muted
    id: ma_mute_changed

# =============================================================================
# VARIABLES
# =============================================================================
variables:
  alexa_list: !input alexa_players
  ma_list: !input ma_players
  ducking_flag_entity: !input ducking_flag
  direction: !input sync_direction
  tolerance: !input volume_tolerance
  cooldown: !input sync_cooldown
  only_playing: !input only_sync_when_playing

  # Which trigger fired
  source: "{{ trigger.id }}"
  changed_entity: "{{ trigger.entity_id }}"
  is_volume_trigger: "{{ source in ['alexa_vol_changed', 'ma_vol_changed'] }}"
  is_mute_trigger: "{{ source in ['alexa_mute_changed', 'ma_mute_changed'] }}"
  is_alexa_source: "{{ source in ['alexa_vol_changed', 'alexa_mute_changed'] }}"

  # Find the pair index and partner entity
  pair_index: >
    {% if is_alexa_source %}
      {% set idx = alexa_list.index(changed_entity) if changed_entity in alexa_list else -1 %}
    {% else %}
      {% set idx = ma_list.index(changed_entity) if changed_entity in ma_list else -1 %}
    {% endif %}
    {{ idx }}

  # Source and target entities for this pair
  source_entity: "{{ changed_entity }}"
  target_entity: >
    {% set idx = pair_index | int(-1) %}
    {% if idx >= 0 %}
      {% if is_alexa_source %}
        {{ ma_list[idx] }}
      {% else %}
        {{ alexa_list[idx] }}
      {% endif %}
    {% else %}
      {{ '' }}
    {% endif %}

  # Current volume levels for the pair
  source_vol: "{{ state_attr(source_entity, 'volume_level') | float(0) }}"
  target_vol: "{{ state_attr(target_entity, 'volume_level') | float(0) }}"

  # Current mute states for the pair
  source_muted: "{{ state_attr(source_entity, 'is_volume_muted') | default(false) }}"
  target_muted: "{{ state_attr(target_entity, 'is_volume_muted') | default(false) }}"

  # Volume difference as percentage points (0–100 scale)
  vol_diff: "{{ ((source_vol - target_vol) | abs * 100) | round(1) }}"

  # Direction checks
  alexa_to_ma_allowed: "{{ direction in ['both', 'alexa_to_ma'] }}"
  ma_to_alexa_allowed: "{{ direction in ['both', 'ma_to_alexa'] }}"
  direction_allowed: >
    {% if is_alexa_source %}
      {{ alexa_to_ma_allowed }}
    {% else %}
      {{ ma_to_alexa_allowed }}
    {% endif %}

# =============================================================================
# ACTIONS
# =============================================================================
actions:
  # 0) Bail if we couldn't resolve a pair
  - condition: template
    alias: "Valid pair found"
    value_template: "{{ target_entity | trim != '' }}"

  # 0b) Skip sync if either device is unavailable/unknown
  - condition: template
    alias: "Both devices are available"
    value_template: >-
      {{ states(source_entity) | default('unavailable') not in ['unavailable', 'unknown']
         and states(target_entity) | default('unavailable') not in ['unavailable', 'unknown'] }}

  # 1) Skip sync while Voice PE is ducking volumes
  - condition: template
    alias: "Voice PE ducking not active"
    value_template: "{{ states(ducking_flag_entity) | default('off') != 'on' }}"

  # 2) Check direction is allowed
  - condition: template
    alias: "Sync direction allowed"
    value_template: "{{ direction_allowed }}"

  # 3) Optional: only sync when playing
  - condition: template
    alias: "At least one device is playing (optional)"
    value_template: >
      {% if not only_playing %}
        true
      {% else %}
        {{ states(source_entity) | default('off') == 'playing'
           or states(target_entity) | default('off') == 'playing' }}
      {% endif %}

  # 4) Branch: mute sync vs volume sync
  - alias: "Route by trigger type — mute sync vs volume sync"
    choose:
      # === MUTE SYNC ===
      - alias: "Mute trigger — sync mute state to partner"
        conditions:
          - condition: template
            value_template: "{{ is_mute_trigger }}"
        sequence:
          # Skip if mute states already match
          - condition: template
            alias: "Mute states differ"
            value_template: "{{ source_muted != target_muted }}"
          - alias: "Sync mute state to partner device"
            action: media_player.volume_mute
            target:
              entity_id: "{{ target_entity }}"
            data:
              is_volume_muted: "{{ source_muted }}"

    # === VOLUME SYNC (default) ===
    default:
      # Skip if difference is within tolerance AND mute states match
      - condition: template
        alias: "Volume difference exceeds tolerance or mute states differ"
        value_template: >
          {{ vol_diff >= tolerance | float(3) or
             source_muted != target_muted }}

      # Cooldown delay to absorb rapid changes
      - alias: "Cooldown — absorb rapid volume changes"
        delay:
          seconds: "{{ cooldown | float(1) }}"

      # Re-read source volume after cooldown
      - alias: "Re-read source volume after cooldown"
        variables:
          fresh_source_vol: "{{ state_attr(source_entity, 'volume_level') | float(0) }}"

      # Sync mute state (vol=0 → mute, vol>0 → unmute)
      - alias: "Sync mute state — mute if volume is zero"
        action: media_player.volume_mute
        target:
          entity_id: "{{ target_entity }}"
        data:
          is_volume_muted: "{{ fresh_source_vol == 0 }}"

      # Sync volume level
      - alias: "Sync volume level to partner device"
        action: media_player.volume_set
        target:
          entity_id: "{{ target_entity }}"
        data:
          volume_level: "{{ fresh_source_vol }}"

mode: queued
max: 4
max_exceeded: silent
