blueprint:
  name: Automation trigger monitor (multi)
  description: >
    Writes a line to Home Assistant's system_log whenever any of the selected
    automations is triggered. Optionally logs the states of extra entities
    (e.g. presence sensors) at that moment.
  domain: automation
  source_url: https://chatgpt.quark/automation_trigger_monitor_multi
  input:
    monitored_automations:
      name: Automations to monitor
      description: >
        Pick one or more automations you want to log whenever they are
        triggered. Do NOT include this monitor automation itself.
      selector:
        entity:
          domain: automation
          multiple: true

    entities_to_log:
      name: Extra entities to log (optional)
      description: >
        Optional: entities whose states should be included in the log line
        when a monitored automation fires (e.g. bed/workshop/bathroom sensors).
      default: []
      selector:
        entity:
          multiple: true

mode: queued

variables:
  v_automations: !input monitored_automations
  v_entities: !input entities_to_log

trigger:
  - platform: event
    event_type: automation_triggered

condition:
  - condition: template
    alias: Only monitored automations
    value_template: >
      {{ trigger.event.data.entity_id in v_automations }}

action:
  - alias: "Write debug line to system_log"
    service: system_log.write
    data:
      level: info
      message: >
        [Automation monitor] {{ now() }} - {{ trigger.event.data.entity_id }}
        ({{ trigger.event.data.name | default('Unnamed automation') }})
        triggered via {{ trigger.event.data.source | default('unknown') }}.
        {% if v_entities | count > 0 %}
        States at trigger time:
        {% for e in v_entities %}
        {{ e }}={{ states(e) }}
        {% endfor %}
        {% endif %}
