blueprint:
  name: "Coming home – AI welcome"
  author: madalone
  description: >
    ![Image](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/coming_home-header.jpeg)

    # Coming home – AI welcome

    Triggers when a person arrives home, waits for entrance occupancy to
    confirm physical presence (GPS alone isn't reliable), resets speakers by
    power-cycling switches, activates temporary helper switches, generates an
    AI greeting via a conversation agent, then starts an Assist conversation
    on Voice PE satellites. Includes GPS-bounce cooldown, timeout handling on
    every wait, and guaranteed cleanup of temporary switches on all exit paths.

    ### Recent changes
    - **v2:** Full style guide compliance — collapsible sections, modern syntax, aliases, variable scope fix
    - **v1:** Initial version
  domain: automation
  homeassistant:
    min_version: "2024.10.0"
  input:
    person_entity:
      name: Person
      description: >-
        Person entity whose home/not_home state transition triggers this
        automation. The person's friendly_name is used in the AI greeting.
      selector:
        entity:
          domain: person

    # ===========================================================================
    # ① DETECTION & TRIGGERS
    # ===========================================================================
    detection:
      name: "① Detection & triggers"
      icon: mdi:motion-sensor
      description: >-
        Configure how arrival is detected and how aggressively GPS bounces
        are filtered.
      input:
        entrance_sensor:
          name: Entrance occupancy sensor
          description: >-
            Binary sensor that confirms physical presence at the entrance.
            The automation won't proceed on GPS alone — it waits for this
            sensor to trigger before resetting speakers or greeting.
          selector:
            entity:
              domain: binary_sensor
              device_class: occupancy

        entrance_wait_timeout:
          name: Entrance wait timeout
          description: >-
            How long to wait for the entrance sensor after the GPS state
            changes to "home". If nobody is detected within this window,
            the automation aborts cleanly (likely a GPS bounce).
          default: "0:02:00"
          selector:
            duration: {}

        cooldown_seconds:
          name: Cooldown (seconds)
          description: >-
            Minimum seconds between runs to suppress GPS bounce re-triggers.
            If the automation ran within this window, the condition block
            skips execution entirely.
          default: 900
          selector:
            number:
              min: 60
              max: 3600
              unit_of_measurement: seconds

    # ===========================================================================
    # ② DEVICE PREPARATION
    # ===========================================================================
    preparation:
      name: "② Device preparation"
      icon: mdi:cog-refresh
      description: >-
        Switches to power-cycle (reset speakers/audio chains) and temporary
        helper switches to activate during the arrival flow.
      input:
        reset_switches:
          name: Reset switches
          description: >-
            Switches that will be power-cycled (OFF → delay → ON) to reset
            speakers or audio chains before the greeting plays. This clears
            stale Bluetooth connections and audio routing issues.
          selector:
            target:
              entity:
                domain: switch

        reset_switch_delay:
          name: Reset delay
          description: >-
            Pause between turning reset switches OFF and back ON. Increase
            if your speakers need more time to fully power down before
            reconnecting.
          default: "0:00:02"
          selector:
            duration: {}

        arrival_switches:
          name: Temporary switches
          description: >-
            Switches to activate during the arrival flow (e.g., helper
            booleans, relay flags). They are turned ON when the flow starts
            and guaranteed to turn OFF on every exit path — including
            timeouts and aborts.
          selector:
            target:
              entity:
                domain: switch

    # ===========================================================================
    # ③ AI CONVERSATION
    # ===========================================================================
    conversation:
      name: "③ AI conversation"
      icon: mdi:robot-outline
      description: >-
        Conversation agent, greeting prompt, and satellite targeting for
        the AI-generated welcome interaction.
      input:
        conversation_agent:
          name: Conversation / LLM agent
          description: >-
            Conversation agent that generates the arrival greeting and handles
            the follow-up interaction. Can be Extended OpenAI Conversation,
            OpenAI Conversation, or any agent supporting conversation.process.
            The agent's own system prompt handles personality and device
            permissions — this blueprint only passes dynamic arrival context.
          selector:
            conversation_agent:

        ai_greeting_prompt:
          name: AI greeting prompt
          description: >-
            Prompt sent to the conversation agent to generate the first spoken
            line. Use {{ person_name }} to insert the arriving person's name.
            Keep it focused — one instruction, one expected output format.
          default: >-
            {{ person_name }} has just arrived home and walked through the
            entrance. Generate ONE short, snarky greeting that directly
            addresses {{ person_name }} and invites them to choose between
            the workshop lights, the living room lights, or both. Do NOT
            control any devices in this response. Just return the line you
            would say.
          selector:
            text:
              multiline: true

        assist_satellites:
          name: Assist satellites
          description: >-
            Voice PE or Assist satellite entities that should speak the
            AI-generated greeting and handle the follow-up conversation.
            Multiple satellites can be targeted for whole-house announcements.
          selector:
            target:
              entity:
                domain: assist_satellite

    # ===========================================================================
    # ④ CLEANUP & TIMING
    # ===========================================================================
    cleanup:
      name: "④ Cleanup & timing"
      icon: mdi:broom
      description: >-
        Post-conversation delay before temporary switches are turned off.
      input:
        post_conversation_delay:
          name: Post-conversation delay
          description: >-
            How long to wait after starting the Assist conversation before
            turning off temporary switches. Set this long enough for the
            user to finish interacting with the agent.
          default: "0:01:00"
          selector:
            duration: {}

trigger_variables:
  cooldown_seconds: !input cooldown_seconds

variables:
  person_entity: !input person_entity
  person_name: "{{ state_attr(person_entity, 'friendly_name') | default('someone') }}"

triggers:
  - alias: "Person arrives home — GPS state changes to home"
    trigger: state
    entity_id: !input person_entity
    from: not_home
    to: home

conditions:
  - alias: "GPS bounce protection — skip if automation ran recently"
    condition: template
    value_template: >-
      {{ (now() - (this.attributes.last_triggered
         | default(as_datetime('2000-01-01'), true)))
         .total_seconds() > (cooldown_seconds | int(900)) }}

actions:
  - alias: "Wait for entrance occupancy — GPS alone isn't reliable enough"
    wait_for_trigger:
      - trigger: state
        entity_id: !input entrance_sensor
        to: "on"
    timeout: !input entrance_wait_timeout
    continue_on_timeout: true

  - alias: "Handle entrance timeout — clean up if nobody physically arrived"
    if:
      - condition: template
        value_template: "{{ not wait.completed }}"
    then:
      - stop: "Entrance sensor timed out — nobody showed up. Aborting."

  - alias: "Reset speakers — power-cycle OFF to clear stale connections"
    action: switch.turn_off
    target: !input reset_switches

  - alias: "Wait for speaker hardware to fully power down"
    delay: !input reset_switch_delay

  - alias: "Reset speakers — power-cycle back ON"
    action: switch.turn_on
    target: !input reset_switches

  - alias: "Activate temporary switches for arrival flow"
    action: switch.turn_on
    target: !input arrival_switches

  - alias: "Wait for entrance to clear — person moved past the door"
    wait_for_trigger:
      - trigger: state
        entity_id: !input entrance_sensor
        to: "off"
    timeout: !input entrance_wait_timeout
    continue_on_timeout: true

  - alias: "Handle entrance-clear timeout — clean up and abort"
    if:
      - condition: template
        value_template: "{{ not wait.completed }}"
    then:
      - alias: "Clean up temporary switches before aborting"
        action: switch.turn_off
        target: !input arrival_switches
      - stop: "Entrance never cleared — aborting and cleaning up."

  - alias: "Generate AI greeting via conversation agent"
    action: conversation.process
    response_variable: ai_greeting
    data:
      agent_id: !input conversation_agent
      text: !input ai_greeting_prompt
    continue_on_error: true

  - alias: "Extract greeting text with fallback if LLM failed"
    variables:
      welcome_line: >-
        {% if ai_greeting is defined
           and ai_greeting.response is defined
           and ai_greeting.response.speech is defined %}
          {{ ai_greeting.response.speech.plain.speech
             | default("Yo " ~ person_name ~ ", you're back. Workshop, living room, or both?") }}
        {% else %}
          Yo {{ person_name }}, you're back. Workshop, living room, or both?
        {% endif %}

  - alias: "Start Assist conversation on satellites — agent handles the rest"
    action: assist_satellite.start_conversation
    target: !input assist_satellites
    data:
      preannounce: true
      start_message: "{{ welcome_line }}"
      extra_system_prompt: >-
        {{ person_name }} just arrived home and heard: "{{ welcome_line }}".
        This is an arrival conversation. Help them set up their lights, TV,
        and music as per your rules.
    continue_on_error: true

  - alias: "Post-conversation cooldown before cleanup"
    delay: !input post_conversation_delay

  - alias: "Clean up — turn off all temporary switches"
    action: switch.turn_off
    target: !input arrival_switches

mode: restart
