blueprint:
  name: "Coming home – AI welcome"
  author: madalone
  description: >
    ![Image](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/coming_home-header.jpeg)

    # Coming home – AI welcome

    Triggers when a person arrives home, waits for entrance occupancy to
    confirm physical presence (GPS alone isn't reliable), resets speakers by
    power-cycling switches, activates temporary helper switches, generates an
    AI greeting via a conversation agent, then starts an Assist conversation
    on Voice PE satellites. Includes GPS-bounce cooldown, timeout handling on
    every wait, and guaranteed cleanup of temporary switches on all exit paths.

    **Note:** Uses `mode: restart` — if a second person arrives while the first
    flow is running, the first run is cancelled and temporary switches may
    remain ON until the new run completes its cleanup.

    ### Recent changes
    - **v4.4:** Audit fix — added `continue_on_error: true` to logbook.log
      action that was blocking the cleanup path on failure (AP-06).
    - **v4.3:** Audit remediation — fixed entrance sensor race condition where
      wait_for_trigger missed already-on state (AP-20), added restart-safe
      cleanup preamble to handle stale switches from interrupted runs (AP-23),
      added missing aliases on 2 switch.turn_off actions (AP-11), added
      logbook entry after satellite greeting for troubleshooting (AP-17).
    - **v4.2:** Added defaults to person_entities, entrance_sensor,
      conversation_agent, and assist_satellites so all four sections render
      as collapsible in the HA UI. Inputs are technically optional but the
      automation will not function without them.
    - **v4.1:** Section structure — moved `person_entities` and `person_names`
      into Section ① (detection), added explicit `collapsed: false` to
      Section ① header per §3.2.
    - **v4:** Audit remediation — fixed person identification bug (greets
      triggering person, not all configured), hardened LLM response parsing
      with chained `.get()` guards, made person_entities required, converted
      arrival_switches to optional entity selector with choose guards,
      added `collapsed: true` to sections ②③④, added `continue_on_error`
      to reset switch actions, documented restart-mode cleanup gap.
    - **v3:** Multi-person support — person selector accepts multiple entities,
      new multiline text field for custom arrival names (overrides entity
      friendly names). Reset switches now optional (empty = skip power-cycle).
    - **v2:** Full style guide compliance — collapsible sections, modern syntax, aliases, variable scope fix
    - **v1:** Initial version
  domain: automation
  homeassistant:
    min_version: "2024.10.0"
  input:
    # ===========================================================================
    # ① DETECTION & TRIGGERS
    # ===========================================================================
    detection:
      name: "① Detection & triggers"
      icon: mdi:motion-sensor
      collapsed: false
      description: >-
        Configure how arrival is detected and how aggressively GPS bounces
        are filtered.
      input:
        person_entities:
          name: Persons
          description: >-
            Person entities whose home/not_home state transition triggers this
            automation. When any selected person arrives home, the flow runs.
            The triggering person's friendly name is used in the AI greeting
            unless overridden by the arrival names field below. At least one
            person entity is required — the automation cannot fire without it.
          default: []
          selector:
            entity:
              domain: person
              multiple: true

        person_names:
          name: Arrival names (optional)
          description: >-
            Custom names to use in the AI greeting. One name per line. When
            provided, these override the person entity friendly names in the
            greeting prompt. Useful when the arriving party includes people
            without HA person entities (partner, guest, frequent visitor).
          default: ""
          selector:
            text:
              multiline: true

        entrance_sensor:
          name: Entrance occupancy sensor
          description: >-
            Binary sensor that confirms physical presence at the entrance.
            The automation won't proceed on GPS alone — it waits for this
            sensor to trigger before resetting speakers or greeting.
          default: ""
          selector:
            entity:
              domain: binary_sensor
              device_class: occupancy

        entrance_wait_timeout:
          name: Entrance wait timeout
          description: >-
            How long to wait for the entrance sensor after the GPS state
            changes to "home". If nobody is detected within this window,
            the automation aborts cleanly (likely a GPS bounce).
          default: "0:02:00"
          selector:
            duration: {}

        cooldown_seconds:
          name: Cooldown (seconds)
          description: >-
            Minimum seconds between runs to suppress GPS bounce re-triggers.
            If the automation ran within this window, the condition block
            skips execution entirely.
          default: 900
          selector:
            number:
              min: 60
              max: 3600
              unit_of_measurement: seconds

    # ===========================================================================
    # ② DEVICE PREPARATION
    # ===========================================================================
    preparation:
      name: "② Device preparation"
      icon: mdi:cog-refresh
      collapsed: true
      description: >-
        Switches to power-cycle (reset speakers/audio chains) and temporary
        helper switches to activate during the arrival flow.
      input:
        reset_switches:
          name: Reset switches (optional)
          description: >-
            Switches to power-cycle (OFF → delay → ON) to reset speakers or
            audio chains before the greeting plays. Clears stale Bluetooth
            connections and audio routing issues. Leave empty to skip the
            power-cycle step entirely.
          default: []
          selector:
            entity:
              domain: switch
              multiple: true

        reset_switch_delay:
          name: Reset delay
          description: >-
            Pause between turning reset switches OFF and back ON. Increase
            if your speakers need more time to fully power down before
            reconnecting.
          default: "0:00:02"
          selector:
            duration: {}

        arrival_switches:
          name: Temporary switches (optional)
          description: >-
            Switch entities to activate during the arrival flow (e.g., helper
            booleans, relay flags). They are turned ON when the flow starts
            and guaranteed to turn OFF on every exit path — including
            timeouts and aborts. Leave empty to skip.
          default: []
          selector:
            entity:
              domain: switch
              multiple: true

    # ===========================================================================
    # ③ AI CONVERSATION
    # ===========================================================================
    conversation:
      name: "③ AI conversation"
      icon: mdi:robot-outline
      collapsed: true
      description: >-
        Conversation agent, greeting prompt, and satellite targeting for
        the AI-generated welcome interaction.
      input:
        conversation_agent:
          name: Conversation / LLM agent
          description: >-
            Conversation agent that generates the arrival greeting and handles
            the follow-up interaction. Can be Extended OpenAI Conversation,
            OpenAI Conversation, or any agent supporting conversation.process.
            The agent's own system prompt handles personality and device
            permissions — this blueprint only passes dynamic arrival context.
          default: ""
          selector:
            conversation_agent:

        ai_greeting_prompt:
          name: AI greeting prompt
          description: >-
            Prompt sent to the conversation agent to generate the first spoken
            line. Use {{ person_name }} to insert the arriving person's name.
            Keep it focused — one instruction, one expected output format.
          default: >-
            {{ person_name }} has just arrived home and walked through the
            entrance. Generate ONE short, snarky greeting that directly
            addresses {{ person_name }} and invites them to choose between
            the workshop lights, the living room lights, or both. Do NOT
            control any devices in this response. Just return the line you
            would say.
          selector:
            text:
              multiline: true

        assist_satellites:
          name: Assist satellites
          description: >-
            Voice PE or Assist satellite entities that should speak the
            AI-generated greeting and handle the follow-up conversation.
            Multiple satellites can be targeted for whole-house announcements.
          default: {}
          selector:
            target:
              entity:
                domain: assist_satellite

    # ===========================================================================
    # ④ CLEANUP & TIMING
    # ===========================================================================
    cleanup:
      name: "④ Cleanup & timing"
      icon: mdi:broom
      collapsed: true
      description: >-
        Post-conversation delay before temporary switches are turned off.
      input:
        post_conversation_delay:
          name: Post-conversation delay
          description: >-
            How long to wait after starting the Assist conversation before
            turning off temporary switches. Set this long enough for the
            user to finish interacting with the agent.
          default: "0:01:00"
          selector:
            duration: {}

trigger_variables:
  cooldown_seconds: !input cooldown_seconds

variables:
  person_names_raw: !input person_names
  reset_switches_list: !input reset_switches
  arrival_switches_list: !input arrival_switches
  person_name: >-
    {% set custom = person_names_raw | string | trim %}
    {% if custom != '' %}
      {{ custom.split('\n') | map('trim') | reject('equalto', '') | join(' and ') }}
    {% elif trigger is defined and trigger.entity_id is defined %}
      {{ state_attr(trigger.entity_id, 'friendly_name') | default('someone') }}
    {% else %}
      someone
    {% endif %}

triggers:
  - alias: "Person arrives home — GPS state changes to home"
    trigger: state
    entity_id: !input person_entities
    from: not_home
    to: home

conditions:
  - alias: "GPS bounce protection — skip if automation ran recently"
    condition: template
    value_template: >-
      {{ (now() - (this.attributes.last_triggered
         | default(as_datetime('2000-01-01'), true)))
         .total_seconds() > (cooldown_seconds | int(900)) }}

actions:
  - alias: "Restart-safe cleanup — turn off stale arrival switches from interrupted runs"
    choose:
      - alias: "Arrival switches are configured"
        conditions:
          - condition: template
            value_template: "{{ arrival_switches_list | length > 0 }}"
        sequence:
          - alias: "Turn off stale temporary switches from previous interrupted run"
            action: switch.turn_off
            target:
              entity_id: "{{ arrival_switches_list }}"
            continue_on_error: true

  - alias: "Check if entrance sensor is already triggered (skip wait if so)"
    if:
      - condition: state
        entity_id: !input entrance_sensor
        state: "on"
    then: []
    else:
      - alias: "Wait for entrance occupancy — GPS alone isn't reliable enough"
        wait_for_trigger:
          - trigger: state
            entity_id: !input entrance_sensor
            to: "on"
        timeout: !input entrance_wait_timeout
        continue_on_timeout: true

      - alias: "Handle entrance timeout — clean up if nobody physically arrived"
        if:
          - condition: template
            value_template: "{{ not wait.completed }}"
        then:
          - stop: "Entrance sensor timed out — nobody showed up. Aborting."

  - alias: "Reset speakers — power-cycle to clear stale connections (optional, skipped if no switches configured)"
    choose:
      - alias: "Reset switches are configured"
        conditions:
          - condition: template
            value_template: "{{ reset_switches_list | length > 0 }}"
        sequence:
          - alias: "Reset speakers — power-cycle OFF to clear stale connections"
            action: switch.turn_off
            target:
              entity_id: "{{ reset_switches_list }}"
            continue_on_error: true

          - alias: "Wait for speaker hardware to fully power down"
            delay: !input reset_switch_delay

          - alias: "Reset speakers — power-cycle back ON"
            action: switch.turn_on
            target:
              entity_id: "{{ reset_switches_list }}"
            continue_on_error: true

  - alias: "Activate temporary switches for arrival flow (optional, skipped if none configured)"
    choose:
      - alias: "Arrival switches are configured"
        conditions:
          - condition: template
            value_template: "{{ arrival_switches_list | length > 0 }}"
        sequence:
          - alias: "Turn on temporary switches"
            action: switch.turn_on
            target:
              entity_id: "{{ arrival_switches_list }}"

  - alias: "Wait for entrance to clear — person moved past the door"
    wait_for_trigger:
      - trigger: state
        entity_id: !input entrance_sensor
        to: "off"
    timeout: !input entrance_wait_timeout
    continue_on_timeout: true

  - alias: "Handle entrance-clear timeout — clean up and abort"
    if:
      - condition: template
        value_template: "{{ not wait.completed }}"
    then:
      - alias: "Clean up temporary switches before aborting"
        choose:
          - alias: "Arrival switches are configured"
            conditions:
              - condition: template
                value_template: "{{ arrival_switches_list | length > 0 }}"
            sequence:
              - alias: "Turn off temporary arrival switches before aborting"
                action: switch.turn_off
                target:
                  entity_id: "{{ arrival_switches_list }}"
      - stop: "Entrance never cleared — aborting and cleaning up."

  - alias: "Generate AI greeting via conversation agent"
    action: conversation.process
    response_variable: ai_greeting
    data:
      agent_id: !input conversation_agent
      text: !input ai_greeting_prompt
    continue_on_error: true

  - alias: "Extract greeting text with fallback if LLM failed"
    variables:
      welcome_line: >-
        {% set fallback = "Yo " ~ person_name ~ ", you're back. Workshop, living room, or both?" %}
        {% set resp = (ai_greeting | default({})) %}
        {% set speech_obj = resp.get('response', {}).get('speech', {}).get('plain', {}) %}
        {{ speech_obj.get('speech', '') | default(fallback, true) }}

  - alias: "Start Assist conversation on satellites — agent handles the rest"
    action: assist_satellite.start_conversation
    target: !input assist_satellites
    data:
      preannounce: true
      start_message: "{{ welcome_line }}"
      extra_system_prompt: >-
        {{ person_name }} just arrived home and heard: "{{ welcome_line }}".
        This is an arrival conversation. Help them set up their lights, TV,
        and music as per your rules.
    continue_on_error: true

  - alias: "Log greeting attempt for troubleshooting silent satellite failures"
    action: logbook.log
    data:
      name: "Coming Home"
      message: "Arrival greeting sent for {{ person_name }}: {{ welcome_line[:80] }}"
      entity_id: !input entrance_sensor
    continue_on_error: true

  - alias: "Post-conversation cooldown before cleanup"
    delay: !input post_conversation_delay

  - alias: "Clean up — turn off all temporary switches (optional, skipped if none configured)"
    choose:
      - alias: "Arrival switches are configured"
        conditions:
          - condition: template
            value_template: "{{ arrival_switches_list | length > 0 }}"
        sequence:
          - alias: "Turn off temporary arrival switches (final cleanup)"
            action: switch.turn_off
            target:
              entity_id: "{{ arrival_switches_list }}"

mode: restart
