blueprint:
  name: Music Assistant – Follow Me (idle OFF + optional auto-ON)
  author: madalone
  description: |
    ![Image](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/music_assistant_follow_me_idle_off-header.jpeg)

    ## Music Assistant – Manage Follow Me toggle

    This automation manages your `music_follow_me` (or similar) toggle:
      - Option 1: **Auto-disable** when all players are idle for X minutes.
      - Option 2 (optional): **Auto-enable** when any monitored player starts playing.

    ### What this does

    - Triggers on *any* state change of the selected Music Assistant players.
    - On each trigger it calculates:
      - `all_idle` → all monitored players are non-playing for at least `Idle minutes`.
      - `any_playing` → at least one monitored player is `playing`.

    Then it does:

    1. **Turn OFF** the follow switch when:
       - Follow switch is **ON**, and
       - `all_idle` is **true**.

    2. **Turn ON** the follow switch when:
       - `Auto-enable on playback` is **true**, and
       - Follow switch is **OFF**, and
       - `any_playing` is **true**.

    These two branches are mutually exclusive:
      - It only turns OFF when the switch is currently ON.
      - It only turns ON when the switch is currently OFF.

    ### Typical setup

    - Use this together with your "Music Assistant – Follow Me (multi-room)"
      blueprint which actually moves the queue based on presence sensors.
    - This one just manages the **input_boolean** that gates that behaviour.

    ### Inputs

    - **Follow music toggle**:
      The input_boolean (e.g. `input_boolean.music_follow_me`).

    - **Music players to monitor**:
      All Music Assistant players that may hold your queue.

    - **Idle minutes**:
      How long ALL those players must be idle before auto-disabling.

    - **Auto-enable on playback**:
      If true, starting MA playback on any monitored player will
      automatically turn the follow switch ON.

    ### Recent changes
    - **v2:** Style guide compliance — modern syntax, aliases, collapsible inputs, header image
    - **v1:** Initial version

  domain: automation
  source_url: https://github.com/mmadalone/HA-Master-Repo/blob/main/automation/music_assistant_follow_me_idle_off.yaml

  input:
    # ===========================================================================
    # ① CORE SETTINGS
    # ===========================================================================
    core_settings:
      name: "① Core settings"
      icon: mdi:music-note
      collapsed: false
      description: The toggle and players this automation manages.
      input:
        follow_switch:
          name: Follow music toggle
          description: >
            The input_boolean that enables/disables your "music follows me"
            behaviour. Typically `input_boolean.music_follow_me`.
          selector:
            entity:
              domain: input_boolean
          default: ""

        music_players:
          name: Music players to monitor
          description: >
            One or more **Music Assistant** media_player entities that may hold
            your queues (workshop, living room, bathroom, etc.).
          selector:
            entity:
              domain: media_player
              multiple: true
          default: ""

    # ===========================================================================
    # ② BEHAVIOR
    # ===========================================================================
    behavior:
      name: "② Behavior"
      icon: mdi:cog-outline
      collapsed: true
      description: Idle timeout and auto-enable settings.
      input:
        idle_minutes:
          name: Idle minutes before disabling
          description: >
            If ALL selected players have been non-playing for at least this many
            minutes, the follow toggle will be turned OFF.
          default: 15
          selector:
            number:
              min: 1
              max: 180
              unit_of_measurement: minutes
              mode: slider

        auto_enable_on_play:
          name: Auto-enable on playback
          description: >
            When enabled, if the follow toggle is OFF and any monitored player
            starts playing, this automation will turn the follow toggle ON.
          default: true
          selector:
            boolean: {}

mode: single
max_exceeded: silent

variables:
  players: !input music_players
  idle_minutes: !input idle_minutes
  follow_switch_entity: !input follow_switch
  auto_enable_on_play: !input auto_enable_on_play

triggers:
  - alias: "Any monitored player changes state — re-evaluate idle and playback"
    id: player_state_change
    trigger: state
    entity_id: !input music_players

actions:
  - alias: "Compute idle and playback state across all monitored players"
    variables:
      all_idle: >
        {% set now_ts = as_timestamp(now()) %}
        {% set idle_secs = (idle_minutes | int) * 60 %}
        {% set ns = namespace(all_idle=true) %}

        {% for p in expand(players) %}
          {# If any player is currently playing, we are not idle #}
          {% if p.state == 'playing' %}
            {% set ns.all_idle = false %}
          {# If last change was too recent, we haven't been idle long enough #}
          {% elif now_ts - as_timestamp(p.last_changed | default(now())) < idle_secs %}
            {% set ns.all_idle = false %}
          {% endif %}
        {% endfor %}

        {{ ns.all_idle }}

      any_playing: >
        {% set ns = namespace(any_play=false) %}
        {% for p in expand(players) %}
          {% if p.state == 'playing' %}
            {% set ns.any_play = true %}
          {% endif %}
        {% endfor %}
        {{ ns.any_play }}

  - alias: "Branch — auto-OFF when idle vs auto-ON when playback starts"
    choose:
      # Branch 1: auto-OFF when idle long enough
      - alias: "Auto-OFF — all players idle beyond threshold"
        conditions:
          - condition: template
            value_template: "{{ is_state(follow_switch_entity, 'on') }}"
          - condition: template
            value_template: "{{ all_idle | bool }}"
        sequence:
          - alias: "Turn off follow switch — all players idle"
            action: input_boolean.turn_off
            target:
              entity_id: !input follow_switch

      # Branch 2: auto-ON when playback starts (optional)
      - alias: "Auto-ON — playback detected while follow is off"
        conditions:
          - condition: template
            value_template: "{{ auto_enable_on_play | bool }}"
          - condition: template
            value_template: "{{ is_state(follow_switch_entity, 'off') }}"
          - condition: template
            value_template: "{{ any_playing | bool }}"
        sequence:
          - alias: "Turn on follow switch — playback started"
            action: input_boolean.turn_on
            target:
              entity_id: !input follow_switch
