blueprint:
  name: "Proactive – Presence-based suggestions (v6)"
  author: madalone
  description: >
    ![Image](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/proactive-header.jpeg)

    # Proactive – Presence-based suggestions

    When presence is detected in an area during a configured time window,
    proactively speaks a message via TTS. Messages are read from
    input_text helpers (morning/afternoon/evening), so they can be
    generated or refreshed by another automation. Includes configurable
    cooldown, nag-while-present mode, post-run refresh, and an optional
    bedtime yes/no question via Assist Satellite.

    ### Recent changes
    - **v6:** Audit fixes — added `source_url`, TTS `choose` default fallback branch, gated bedtime trigger on `enable_bedtime_question`, companion README
    - **v5:** Collapsible section audit — added `collapsed:` to all sections, defaults on all entity inputs
    - **v4:** Style guide compliance — collapsible sections, modern syntax, template safety
    - **v3:** Added bedtime question via Assist Satellite, nag limits
    - **v2:** Added ElevenLabs custom TTS mode, refresh button support
  domain: automation
  source_url: "https://github.com/mmadalone/HA-Master-Repo/blob/main/automation/proactive.yaml"
  homeassistant:
    min_version: "2024.10.0"

  input:
    # ===========================================================================
    # ① DETECTION
    # ===========================================================================
    detection:
      name: "① Detection"
      icon: mdi:motion-sensor
      description: Presence sensors that trigger the proactive message.
      collapsed: false
      input:
        presence_sensors:
          name: Presence sensors for this area
          description: >
            One or more binary sensors that indicate presence in this area
            (e.g. FP2 room groups for Living room, Workshop, etc.).
            The automation fires when ANY of these turns on.
          selector:
            entity:
              domain: binary_sensor
              multiple: true
          default: ""

        area_name:
          name: Area name (for the message)
          description: >
            Friendly name of this area, used in fallback messages and
            can be referenced in AI-generated text. Pick from the menu
            or type your own value.
          default: ""
          selector:
            select:
              options:
                - Workshop
                - Living room
                - Bedroom
                - Office
                - Kitchen
                - Bathroom
              custom_value: true

    # ===========================================================================
    # ② TTS CONFIGURATION
    # ===========================================================================
    tts_config:
      name: "② TTS configuration"
      icon: mdi:text-to-speech
      description: Speaker and text-to-speech engine settings.
      collapsed: true
      input:
        media_player:
          name: Speaker / media player to speak from
          description: >
            Media player to use for TTS in this area.
            Can be a Voice PE speaker, Sonos, etc.
          default: {}
          selector:
            entity:
              domain: media_player

        tts_mode:
          name: TTS mode
          description: >
            Choose how TTS is delivered:
            "standard_tts_entity" uses any TTS entity via tts.speak.
            "elevenlabs_custom_service" uses the HACS ElevenLabs custom
            integration with options.voice_profile.
          default: standard_tts_entity
          selector:
            select:
              options:
                - standard_tts_entity
                - elevenlabs_custom_service

        tts_entity:
          name: TTS entity to use with tts.speak
          description: >
            TTS entity used by tts.speak. Examples: tts.elevenlabs
            (official), tts.elevenlabs_custom_tts (HACS custom), or
            any other TTS entity.
          default: {}
          selector:
            entity:
              domain: tts

        elevenlabs_voice_profile:
          name: ElevenLabs voice profile (for custom mode)
          description: >
            Only used when TTS mode is "elevenlabs_custom_service".
            Voice profile name/ID for the ElevenLabs custom integration,
            e.g. "Quark - Custom 11". Must match your tts.speak
            options.voice_profile value.
          default: ""
          selector:
            text:
              multiline: false

    # ===========================================================================
    # ③ SCHEDULE & TIMING
    # ===========================================================================
    schedule:
      name: "③ Schedule & timing"
      icon: mdi:clock-outline
      description: Active time window and cooldown between messages.
      collapsed: true
      input:
        start_time:
          name: Active from
          description: >
            Start time of the daily window where proactive messages
            are allowed in this area.
          default: "08:00:00"
          selector:
            time: {}

        end_time:
          name: Active until
          description: >
            End time of the daily window. Can be earlier than
            "Active from" to create a window that crosses midnight
            (e.g. 23:00 → 02:00).
          default: "23:00:00"
          selector:
            time: {}

        cooldown_minutes:
          name: Cooldown / nag interval (minutes)
          description: >
            Minimum time between proactive messages. When 'Keep nagging
            while present' is enabled, this acts as the nag interval.
          default: 30
          selector:
            number:
              min: 1
              max: 240
              step: 1
              unit_of_measurement: "min"

    # ===========================================================================
    # ④ NAGGING BEHAVIOR
    # ===========================================================================
    nagging:
      name: "④ Nagging behavior"
      icon: mdi:repeat
      description: Controls for repeated messages while presence persists.
      collapsed: true
      input:
        repeat_while_present:
          name: Keep nagging while present
          description: >
            If enabled, keeps nagging at the cooldown interval as long
            as presence is detected within the active window. If disabled,
            only speaks once when presence turns on (until you leave and
            re-enter).
          default: false
          selector:
            boolean: {}

        max_nags_per_session:
          name: Max nags per presence session (0 = unlimited)
          description: >
            Only used when 'Keep nagging while present' is enabled.
            0 = nag indefinitely until you leave the area.
            >0 = stop nagging after this many messages per session.
            A session ends when all presence sensors turn off.
          default: 0
          selector:
            number:
              min: 0
              max: 20
              step: 1

    # ===========================================================================
    # ⑤ MESSAGE SOURCES
    # ===========================================================================
    messages:
      name: "⑤ Message sources"
      icon: mdi:message-text-outline
      description: Input text helpers storing time-of-day messages, plus optional refresh.
      collapsed: true
      input:
        message_morning_helper:
          name: Morning message input_text
          description: >
            input_text entity storing the MORNING message for this area.
            Typically filled by an AI refresh automation, but can be
            set manually.
          default: {}
          selector:
            entity:
              domain: input_text

        message_afternoon_helper:
          name: Afternoon message input_text
          description: >
            input_text entity storing the AFTERNOON message for this area.
          default: {}
          selector:
            entity:
              domain: input_text

        message_evening_helper:
          name: Evening message input_text
          description: >
            input_text entity storing the EVENING/NIGHT message.
            In bedtime mode this is always the one spoken.
          default: {}
          selector:
            entity:
              domain: input_text

        refresh_after_run:
          name: Refresh messages after each run
          description: >
            If enabled, presses the configured refresh button after
            speaking so a separate AI automation can regenerate messages.
          default: false
          selector:
            boolean: {}

        refresh_button:
          name: Refresh button to press
          description: >
            input_button that triggers the AI "Refresh messages"
            automation for this area. Only pressed if refresh is enabled.
          default: {}
          selector:
            entity:
              domain: input_button

    # ===========================================================================
    # ⑥ BEDTIME
    # ===========================================================================
    bedtime:
      name: "⑥ Bedtime question"
      icon: mdi:bed
      description: Optional bedtime yes/no question via Assist Satellite.
      collapsed: true
      input:
        enable_bedtime_question:
          name: Ask if you want help going to bed
          description: >
            If enabled, after the TTS message, asks a yes/no question
            on the selected Assist Satellite. If you say yes, the
            bedtime script runs. Enable only for bedtime instances.
          default: false
          selector:
            boolean: {}

        bedtime_question_delay:
          name: Delay before bedtime question (seconds)
          description: >
            How long to wait after TTS before asking the bedtime
            question. Needed because some TTS integrations mark the
            player idle before audio finishes.
          default: 5
          selector:
            number:
              min: 0
              max: 30
              unit_of_measurement: seconds
              mode: slider
              step: 1

        bedtime_assist_satellite:
          name: Assist Satellite for bedtime question
          description: >
            Assist Satellite (Voice PE) entity that asks the bedtime
            question. Typically the satellite in the same area as the
            media player.
          default: {}
          selector:
            entity:
              domain: assist_satellite

        bedtime_question_text:
          name: Bedtime question text
          description: >
            The yes/no question to ask, e.g. "Miquel, do you want me
            to help you go to bed now?"
          default: "Miquel, do you want me to help you go to bed now?"
          selector:
            text:
              multiline: true

        bedtime_help_script:
          name: Script to run when you say yes
          description: >
            Script called when the bedtime question is answered YES.
            Should be your 'put me to bed' routine, created separately
            and selected here.
          default: {}
          selector:
            entity:
              domain: script

mode: single
max_exceeded: silent

variables:
  cooldown: !input cooldown_minutes
  refresh_after_run: !input refresh_after_run
  refresh_button: !input refresh_button
  presence_entities: !input presence_sensors
  repeat_while_present: !input repeat_while_present
  max_nags_per_session: !input max_nags_per_session
  enable_bedtime_question: !input enable_bedtime_question
  bedtime_assist_satellite: !input bedtime_assist_satellite
  bedtime_question_text: !input bedtime_question_text
  bedtime_help_script: !input bedtime_help_script
  bedtime_question_delay: !input bedtime_question_delay

triggers:
  - alias: "Presence detected — first nag on arrival"
    id: presence_on
    trigger: state
    entity_id: !input presence_sensors
    from: "off"
    to: "on"

  - alias: "Periodic tick — repeat nag check every five minutes"
    id: periodic_tick
    trigger: time_pattern
    minutes: "/5"

  - alias: "Bedtime — exact start_time trigger each day"
    id: bedtime_time
    trigger: time
    at: !input start_time

conditions:
  - alias: "Within active time window"
    condition: time
    after: !input start_time
    before: !input end_time

  - alias: "Presence still detected in area"
    condition: template
    value_template: >-
      {{ expand(presence_entities)
         | selectattr('state', 'eq', 'on') | list | count > 0 }}

  - alias: "Periodic tick only allowed when repeat mode is on"
    condition: template
    value_template: >-
      {{ repeat_while_present or trigger.id != 'periodic_tick' }}

  - alias: "Bedtime time trigger only fires when bedtime mode is enabled"
    condition: template
    value_template: >-
      {{ enable_bedtime_question or trigger.id != 'bedtime_time' }}

  - alias: "Cooldown and max nags per session"
    condition: template
    value_template: >-
      {% set mins = cooldown | int %}
      {% set max_nags = max_nags_per_session | int %}
      {% set last = this.attributes.last_triggered %}
      {% set enough_time = last is none
        or (as_timestamp(now()) - as_timestamp(last)) > (mins * 60) %}
      {% if not enough_time %}
        false
      {% elif max_nags == 0 %}
        true
      {% else %}
        {% set on_sensors = expand(presence_entities)
          | selectattr('state', 'eq', 'on') | list %}
        {% if on_sensors | count == 0 %}
          true
        {% else %}
          {% set session_start = (on_sensors
              | map(attribute='last_changed') | min) %}
          {% set max_duration = max_nags * mins * 60 %}
          {{ (as_timestamp(now()) - as_timestamp(session_start)) < max_duration }}
        {% endif %}
      {% endif %}

actions:
  - alias: "Resolve inputs and build proactive message"
    variables:
      player: !input media_player
      tts_mode: !input tts_mode
      tts_entity: !input tts_entity
      area_name: !input area_name
      voice_profile: !input elevenlabs_voice_profile
      morning_entity: !input message_morning_helper
      afternoon_entity: !input message_afternoon_helper
      evening_entity: !input message_evening_helper

      tod_label: >-
        {% if enable_bedtime_question %}
          evening
        {% else %}
          {% set h = now().hour %}
          {% if 5 <= h < 12 %}
            morning
          {% elif 12 <= h < 18 %}
            afternoon
          {% else %}
            evening
          {% endif %}
        {% endif %}

      proactive_message: >-
        {% set morning = states(morning_entity) | default('', true) %}
        {% set afternoon = states(afternoon_entity) | default('', true) %}
        {% set evening = states(evening_entity) | default('', true) %}
        {% if tod_label == 'morning' %}
          {% if morning in ['', 'unavailable', 'unknown'] %}
            Good {{ tod_label }}, you just stepped into the {{ area_name }}.
            Want me to start your usual chaos… I mean, music?
          {% else %}
            {{ morning }}
          {% endif %}
        {% elif tod_label == 'afternoon' %}
          {% if afternoon in ['', 'unavailable', 'unknown'] %}
            Back in the {{ area_name }}, huh? Need me to resume your tunes
            or handle something for you?
          {% else %}
            {{ afternoon }}
          {% endif %}
        {% else %}
          {% if evening in ['', 'unavailable', 'unknown'] %}
            It's {{ tod_label }} in the {{ area_name }}.
            I can spin something relaxing or set the mood. Just say the word.
          {% else %}
            {{ evening }}
          {% endif %}
        {% endif %}

  - alias: "Speak proactive message via chosen TTS mode"
    choose:
      - alias: "ElevenLabs custom service with voice profile"
        conditions:
          - condition: template
            value_template: "{{ tts_mode == 'elevenlabs_custom_service' }}"
        sequence:
          - alias: "TTS speak with voice profile option"
            action: tts.speak
            target:
              entity_id: "{{ tts_entity }}"
            data:
              message: "{{ proactive_message }}"
              media_player_entity_id: "{{ player }}"
              options:
                voice_profile: "{{ voice_profile }}"

      - alias: "Standard TTS entity"
        conditions:
          - condition: template
            value_template: "{{ tts_mode == 'standard_tts_entity' }}"
        sequence:
          - alias: "TTS speak via standard entity"
            action: tts.speak
            target:
              entity_id: "{{ tts_entity }}"
            data:
              message: "{{ proactive_message }}"
              media_player_entity_id: "{{ player }}"

    default:
      - alias: "Fallback — unknown TTS mode, log warning and use standard TTS"
        action: system_log.write
        data:
          message: >-
            Proactive blueprint: unknown tts_mode '{{ tts_mode }}'
            — falling back to standard TTS.
          level: warning
      - alias: "Fallback TTS speak"
        action: tts.speak
        target:
          entity_id: "{{ tts_entity }}"
        data:
          message: "{{ proactive_message }}"
          media_player_entity_id: "{{ player }}"

  - alias: "Press refresh button if enabled and not in bedtime mode"
    if:
      - condition: template
        value_template: "{{ refresh_after_run and not enable_bedtime_question }}"
    then:
      - alias: "Press the refresh messages button"
        action: input_button.press
        target:
          entity_id: "{{ refresh_button }}"

  - alias: "Bedtime question flow — ask and handle response"
    if:
      - condition: template
        value_template: "{{ enable_bedtime_question }}"
    then:
      - alias: "Wait for TTS audio to finish before asking"
        delay:
          seconds: "{{ bedtime_question_delay | int }}"

      - alias: "Ask bedtime yes/no question via Assist Satellite"
        action: assist_satellite.ask_question
        continue_on_error: true
        data:
          entity_id: "{{ bedtime_assist_satellite }}"
          question: "{{ bedtime_question_text }}"
          answers:
            - id: "yes"
              sentences:
                - "yes"
                - "yeah"
                - "sure"
                - "ok"
                - "okay"
                - "please"
            - id: "no"
              sentences:
                - "no"
                - "no thanks"
                - "not now"
                - "cancel"
        response_variable: bedtime_answer

      - alias: "Run bedtime script if user said yes"
        choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ bedtime_answer is defined
                     and bedtime_answer.get('id', '') == 'yes' }}
            sequence:
              - alias: "Execute bedtime routine script"
                action: script.turn_on
                target:
                  entity_id: "{{ bedtime_help_script }}"

