blueprint:
  name: "PVR Channel Tracker — Kodi live channel detection"
  author: madalone
  source_url: https://github.com/mmadalone/HA-Master-Repo/
  description: >
    ![Header](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/pvr_channel_tracker-header.jpeg)

    # PVR Channel Tracker

    Monitors a Kodi media player for PVR/live TV content and queries the active
    channel name via `Player.GetItem`. Stores the channel name in an input_text
    helper for use by other automations and template sensors. PVR content is
    fingerprinted by negative or absent `media_season` and `media_episode`
    attributes (covers both native PVR and IPTV Simple Client streams).

    ### Recent changes
    - **v1.2:** Fix IPTV detection — widen PVR fingerprint to catch channels where
      media_season/episode are absent (not just -1). Add [COLOR] tag stripping from
      channel names. Add label fallback for channel name extraction.
    - **v1.1:** Fix feedback loop — add 2s debounce on media_title trigger to prevent
      Kodi JSON-RPC overload from rapid attribute churn (mode: restart + no debounce
      caused tight re-trigger loop that killed the Kodi integration)
    - **v1:** Initial version — single-automation wait_for_trigger pattern
  domain: automation
  homeassistant:
    min_version: "2024.10.0"
  input:
    # ===========================================================================
    # ① CORE SETTINGS
    # ===========================================================================
    core_settings:
      name: "① Core settings"
      icon: mdi:television-classic
      description: Kodi player and channel storage helper.
      input:
        kodi_entity:
          name: Kodi media player
          description: >-
            The Kodi media_player entity to monitor for PVR content.
          selector:
            entity:
              domain: media_player

        pvr_channel_helper:
          name: PVR channel helper
          description: >-
            An input_text helper where the detected channel name will be stored.
            Create one if you don't have it yet (max 255 characters).
          selector:
            entity:
              domain: input_text

    # ===========================================================================
    # ② TIMING
    # ===========================================================================
    timing:
      name: "② Timing"
      icon: mdi:clock-outline
      description: Timeout for the Kodi JSON-RPC response.
      input:
        query_timeout:
          name: Query timeout
          description: >-
            How long to wait for Kodi to respond to the Player.GetItem call
            (seconds). Increase if Kodi is slow or on a remote machine.
          default: 5
          selector:
            number:
              min: 2
              max: 30
              unit_of_measurement: seconds

mode: restart

variables:
  kodi_entity: !input kodi_entity
  pvr_channel_helper: !input pvr_channel_helper
  query_timeout: !input query_timeout

triggers:
  - alias: "Kodi starts playing content"
    trigger: state
    entity_id: !input kodi_entity
    to: "playing"

  - alias: "Kodi title changes while playing — catches channel switches"
    trigger: state
    entity_id: !input kodi_entity
    attribute: media_title
    for: "00:00:02"

conditions:
  - alias: "Kodi is currently playing"
    condition: state
    entity_id: !input kodi_entity
    state: "playing"

  - alias: "Content is PVR/IPTV — season and episode are negative or absent"
    condition: template
    value_template: >-
      {{ (state_attr(kodi_entity, 'media_season') is none
          or state_attr(kodi_entity, 'media_season') | int(0) < 0)
         and
         (state_attr(kodi_entity, 'media_episode') is none
          or state_attr(kodi_entity, 'media_episode') | int(0) < 0) }}

actions:
  - alias: "Query Kodi for active channel via Player.GetItem"
    action: kodi.call_method
    target:
      entity_id: !input kodi_entity
    data:
      method: Player.GetItem
      playerid: 1
      properties:
        - channel
        - channeltype
        - title
    continue_on_error: true

  - alias: "Wait for Kodi JSON-RPC response"
    wait_for_trigger:
      - trigger: event
        event_type: kodi_call_method_result
        event_data:
          entity_id: "{{ kodi_entity }}"
          result_ok: true
    timeout:
      seconds: "{{ query_timeout }}"
    continue_on_timeout: true

  - alias: "Handle timeout — clear helper if Kodi didn't respond"
    if:
      - condition: template
        value_template: "{{ not wait.completed }}"
    then:
      - alias: "Clear channel helper on timeout"
        action: input_text.set_value
        target:
          entity_id: !input pvr_channel_helper
        data:
          value: ""
      - stop: "Kodi did not respond to Player.GetItem within timeout."

  - alias: "Extract channel name from Kodi result"
    variables:
      channel_name: >-
        {% set result = wait.trigger.event.data.result | default({}) %}
        {% set item = result.item | default({}) %}
        {% set raw = item.channel | default(item.label | default('')) | trim %}
        {{ raw | regex_replace('\\[COLOR [^\\]]*\\]', '')
              | regex_replace('\\[/COLOR\\]', '') | trim }}

  - alias: "Store detected channel name in helper"
    action: input_text.set_value
    target:
      entity_id: !input pvr_channel_helper
    data:
      value: "{{ channel_name }}"
