blueprint:
  name: "🚽💡 Smart Bathroom Occupancy Light Control (Door + Shower Zone Optional)"
  author: Murat Çeşmecioğlu (modified by Madalone & Miquel)
  description: '![Image](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/smart-bathroom-header.jpeg)

    # Smart Bathroom Occupancy Light Control

    Occupancy-aware bathroom light with optional door sensor and shower zone
    support. Enable toggles to activate optional sensors — disabled sensors
    are ignored. When shower zone is active (e.g. Aqara FP2 zone), the light
    stays on even if the main motion sensor clears behind a glass shower door.

    ### Recent changes

    - **v3:** Fixed stale variable race condition, consolidated choose blocks, inlined state checks

    - **v2:** Full style guide compliance — modern syntax, timeouts, aliases, collapsible inputs

    - **v1:** Initial version (Murat Çeşmecioğlu, modified by Madalone & Miquel)'
  domain: automation
  homeassistant:
    min_version: "2024.10.0"

  input:
    # ===========================================================================
    # ① SENSORS & DETECTION
    # ===========================================================================
    sensors:
      name: "① Sensors & detection"
      icon: mdi:motion-sensor
      collapsed: false
      description: Configure motion, door, and shower zone sensors.
      input:
        motion_sensor:
          name: Motion Sensor
          description: >-
            Primary motion/occupancy sensor for the bathroom. Detects entry
            and ongoing presence.
          selector:
            entity:
              domain:
                - binary_sensor
              multiple: false
          default: ""

        use_door_sensor:
          name: Use Door Sensor?
          description: >-
            Enable if you have a door/contact sensor. When off, door state
            is ignored in all logic.
          default: false
          selector:
            boolean: {}

        door_sensor:
          name: Door Sensor
          description: >-
            Door/contact sensor entity. Only evaluated when "Use Door Sensor?"
            is enabled — safe to leave empty if disabled.
          default: ""
          selector:
            entity:
              domain:
                - binary_sensor
              device_class:
                - door
                - opening
              multiple: false

        use_shower_zone:
          name: Use Shower Zone Sensor?
          description: >-
            Enable if you have a dedicated presence zone covering the shower
            (e.g. Aqara FP2 zone). Prevents premature light-off while
            showering behind a glass door.
          default: false
          selector:
            boolean: {}

        shower_zone_sensor:
          name: Shower Zone Sensor
          description: >-
            Presence zone sensor for the shower area. Only evaluated when
            "Use Shower Zone Sensor?" is enabled — safe to leave empty
            if disabled.
          default:
          selector:
            entity:
              domain:
                - binary_sensor
              device_class:
                - occupancy
                - presence
                - motion
              multiple: false

    # ===========================================================================
    # ② LIGHTS & HELPERS
    # ===========================================================================
    lights_helpers:
      name: "② Lights & helpers"
      icon: mdi:lightbulb-outline
      collapsed: true
      description: Target light and occupancy tracking helper.
      input:
        light_entity:
          name: Bathroom Light
          description: >-
            The light (or switch/input_boolean) to control. Turned on when
            occupancy is detected, off when the room empties.
          default:
          selector:
            entity:
              filter:
                - domain:
                    - light
                    - switch
                    - input_boolean
              multiple: false

        helper_entity:
          name: Occupancy Helper
          description: >-
            An input_boolean that tracks whether the bathroom is currently
            occupied. Must be a dedicated helper — create one in
            Settings → Helpers if you don't have one.
          default:
          selector:
            entity:
              domain:
                - input_boolean
              multiple: false

    # ===========================================================================
    # ③ TIMING
    # ===========================================================================
    timing:
      name: "③ Timing"
      icon: mdi:clock-outline
      collapsed: true
      description: Motion sensor delay and exit wait timeout.
      input:
        delay_before_motion_check:
          name: Motion Sensor Delay
          description: >-
            How long after the motion sensor clears before treating it as
            "no motion." Accounts for sensor cooldown time. Default 2s.
          default: 2
          selector:
            number:
              min: 0
              max: 60
              step: 1
              unit_of_measurement: s
              mode: slider

        exit_wait_timeout:
          name: Exit Wait Timeout
          description: >-
            Maximum time to wait for motion to stop and shower zone to clear
            after the door opens (branch 5). Prevents the automation from
            hanging indefinitely if a sensor fails. Default 30 minutes.
          default: 30
          selector:
            number:
              min: 5
              max: 120
              step: 5
              unit_of_measurement: min
              mode: slider

mode: single

variables:
  has_door: !input use_door_sensor
  door_entity: !input door_sensor
  has_shower_zone: !input use_shower_zone
  shower_zone: !input shower_zone_sensor
  exit_timeout: !input exit_wait_timeout

triggers:
  - alias: "Door opened — template trigger, only active when door sensor enabled"
    trigger: template
    id: door_opened
    value_template: >-
      {{ has_door and door_entity not in [none, '', {}]
         and is_state(door_entity, 'on') }}

  - alias: "Door closed — template trigger, only active when door sensor enabled"
    trigger: template
    id: door_closed
    value_template: >-
      {{ has_door and door_entity not in [none, '', {}]
         and is_state(door_entity, 'off') }}

  - alias: "Motion detected in bathroom"
    trigger: state
    entity_id: !input motion_sensor
    to: "on"
    id: motion_detected

  - alias: "Motion stopped — cleared after configurable delay"
    trigger: state
    entity_id: !input motion_sensor
    to: "off"
    for:
      seconds: !input delay_before_motion_check
    id: motion_stopped

  - alias: "Shower zone cleared — only active when shower zone enabled"
    trigger: template
    id: shower_zone_cleared
    value_template: >-
      {{ has_shower_zone and shower_zone not in [none, '', {}]
         and is_state(shower_zone, 'off') }}

conditions: []

actions:
  - choose:
      # ── Branch 1: Motion stopped, room empty, no shower → lights off ────────
      - alias: "Motion stopped + (no door or door open) + occupied + no shower → turn off"
        conditions:
          - condition: trigger
            id: motion_stopped
          - condition: template
            value_template: >-
              {{ not has_door
                 or (door_entity not in [none, '', {}]
                     and is_state(door_entity, 'on')) }}
          - condition: state
            entity_id: !input helper_entity
            state: "on"
          - condition: template
            value_template: >-
              {{ not (has_shower_zone
                 and shower_zone not in [none, '', {}]
                 and is_state(shower_zone, 'on')) }}
        sequence:
          - alias: "Turn off bathroom light — room is empty"
            action: homeassistant.turn_off
            target:
              entity_id: !input light_entity

          - alias: "Clear occupancy helper"
            action: input_boolean.turn_off
            target:
              entity_id: !input helper_entity

      # ── Branch 2: Door opened, nobody inside → welcome light ────────────────
      - alias: "Door opened + not occupied → turn on light (someone entering)"
        conditions:
          - condition: trigger
            id: door_opened
          - condition: template
            value_template: "{{ has_door }}"
          - condition: state
            entity_id: !input helper_entity
            state: "off"
        sequence:
          - alias: "Turn on bathroom light — door opened, new entry"
            action: homeassistant.turn_on
            target:
              entity_id: !input light_entity

      # ── Branch 5: Door opened while occupied → wait for exit ────────────────
      # (before Branch 3/4 — door_opened trigger must match here first when
      #  helper is on, otherwise Branch 4's motion_detected would never conflict)
      - alias: "Door opened + occupied → wait for exit (motion stop + shower clear)"
        conditions:
          - condition: trigger
            id: door_opened
          - condition: template
            value_template: "{{ has_door }}"
          - condition: state
            entity_id: !input helper_entity
            state: "on"
        sequence:
          - alias: "Wait for motion to stop — person leaving bathroom"
            wait_for_trigger:
              - trigger: state
                entity_id: !input motion_sensor
                to: "off"
                for:
                  seconds: !input delay_before_motion_check
            timeout:
              minutes: "{{ exit_timeout }}"
            continue_on_timeout: true

          - alias: "Handle motion wait timeout — clean up if sensor never cleared"
            if:
              - condition: template
                value_template: "{{ not wait.completed }}"
            then:
              - alias: "Turn off light — motion wait timed out, forcing cleanup"
                action: homeassistant.turn_off
                target:
                  entity_id: !input light_entity

              - alias: "Clear occupancy helper — timeout cleanup"
                action: input_boolean.turn_off
                target:
                  entity_id: !input helper_entity

              - stop: "Motion sensor timed out after door opened — forced cleanup."

          - alias: "Check if shower zone needs to clear before turning off"
            choose:
              - alias: "Shower zone still active — wait for it to clear"
                conditions:
                  # Live is_state() check — NOT a pre-computed variable (§3.4 caveat:
                  # state may have changed during the preceding motion wait)
                  - condition: template
                    value_template: >-
                      {{ has_shower_zone
                         and shower_zone not in [none, '', {}]
                         and is_state(shower_zone, 'on') }}
                sequence:
                  - alias: "Wait for shower zone to clear"
                    wait_for_trigger:
                      - trigger: template
                        value_template: >-
                          {{ not (has_shower_zone
                             and shower_zone not in [none, '', {}]
                             and is_state(shower_zone, 'on')) }}
                    timeout:
                      minutes: "{{ exit_timeout }}"
                    continue_on_timeout: true

                  - alias: "Handle shower zone wait timeout — clean up if zone never cleared"
                    if:
                      - condition: template
                        value_template: "{{ not wait.completed }}"
                    then:
                      - alias: "Turn off light — shower zone wait timed out"
                        action: homeassistant.turn_off
                        target:
                          entity_id: !input light_entity

                      - alias: "Clear occupancy helper — shower timeout cleanup"
                        action: input_boolean.turn_off
                        target:
                          entity_id: !input helper_entity

                      - stop: "Shower zone timed out — forced cleanup."

          - alias: "Turn off bathroom light — person has left"
            action: homeassistant.turn_off
            target:
              entity_id: !input light_entity

          - alias: "Clear occupancy helper — exit complete"
            action: input_boolean.turn_off
            target:
              entity_id: !input helper_entity

      # ── Branch 4: Motion + door open/no door → light on + mark occupied ─────
      # (before Branch 3 — more specific: handles light AND helper. Branch 3
      #  only fires when this doesn't match, i.e. door is closed)
      - alias: "Motion detected + (no door or door open) → light on and mark occupied"
        conditions:
          - condition: trigger
            id: motion_detected
          - condition: template
            value_template: >-
              {{ not has_door
                 or (door_entity not in [none, '', {}]
                     and is_state(door_entity, 'on')) }}
        sequence:
          - alias: "Turn on bathroom light — motion confirmed with open/no door"
            action: homeassistant.turn_on
            target:
              entity_id: !input light_entity

          - alias: "Set occupancy helper on"
            action: input_boolean.turn_on
            target:
              entity_id: !input helper_entity

      # ── Branch 3: Motion + helper off → mark occupied (door closed case) ────
      - alias: "Motion detected + helper off → mark room as occupied"
        conditions:
          - condition: trigger
            id: motion_detected
          - condition: state
            entity_id: !input helper_entity
            state: "off"
        sequence:
          - alias: "Set occupancy helper on — someone is in the bathroom"
            action: input_boolean.turn_on
            target:
              entity_id: !input helper_entity

      # ── Branch 6: Door closed while not occupied → light off ────────────────
      - alias: "Door closed + not occupied → turn off light"
        conditions:
          - condition: trigger
            id: door_closed
          - condition: template
            value_template: "{{ has_door }}"
          - condition: state
            entity_id: !input helper_entity
            state: "off"
        sequence:
          - alias: "Turn off bathroom light — door closed, nobody inside"
            action: homeassistant.turn_off
            target:
              entity_id: !input light_entity

      # ── Branch 7: Shower cleared + occupied + motion off → turn off ─────────
      - alias: "Shower zone cleared + occupied + motion off + (no door or door open) → turn off"
        conditions:
          - condition: trigger
            id: shower_zone_cleared
          - condition: state
            entity_id: !input helper_entity
            state: "on"
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
          - condition: template
            value_template: >-
              {{ not has_door
                 or (door_entity not in [none, '', {}]
                     and is_state(door_entity, 'on')) }}
        sequence:
          - alias: "Turn off bathroom light — shower zone cleared, motion already off"
            action: homeassistant.turn_off
            target:
              entity_id: !input light_entity

          - alias: "Clear occupancy helper — shower exit complete"
            action: input_boolean.turn_off
            target:
              entity_id: !input helper_entity

    default:
      - alias: "No matching branch — no action needed"
        stop: "No branch matched the current trigger + state combination."
