blueprint:
  name: "Temperature hub – cooling fan per device"
  author: madalone
  description: >
    ![Image](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/temp_hub-header.jpeg)

    # Temperature hub – cooling fan per device

    Generic temperature-based cooling controller. Monitors one
    temperature sensor and turns a smart plug (fan) ON when it is
    above a high threshold and OFF again when it drops below a lower
    threshold. Uses hysteresis to avoid flapping. If the sensor
    becomes unavailable/unknown, the fan is turned OFF as a safety
    fallback. Create one automation instance per device
    (madteevee, retropie, etc).

    ### Recent changes
    - **v2:** Full style guide compliance — modern syntax, aliases, collapsible sections
    - **v1:** Initial version
  domain: automation
  homeassistant:
    min_version: "2024.10.0"

  input:
    # ===========================================================================
    # ① SENSOR & FAN
    # ===========================================================================
    sensor_and_fan:
      name: "① Sensor & fan"
      icon: mdi:fan
      description: Temperature sensor to monitor and fan switch to control.
      collapsed: false
      input:
        temp_sensor:
          name: Temperature sensor
          description: >
            Temperature sensor to monitor for this device
            (e.g. Glances CPU temp from madteevee).
          default: ""
          selector:
            entity:
              domain: sensor
              device_class: temperature

        fan_switch:
          name: Fan smart switch
          description: >
            Smart plug / switch that powers the external fan for this
            device.
          default: ""
          selector:
            entity:
              domain: switch

    # ===========================================================================
    # ② THRESHOLDS
    # ===========================================================================
    thresholds:
      name: "② Thresholds"
      icon: mdi:thermometer-alert
      description: >
        Temperature thresholds for fan control. Set the OFF threshold
        lower than the ON threshold to create hysteresis and avoid flapping.
      collapsed: true
      input:
        high_temp:
          name: Turn fan ON above (°C)
          description: >
            If the temperature is above this value, the fan will be
            turned ON.
          default: 60
          selector:
            number:
              min: 30
              max: 90
              step: 1
              unit_of_measurement: "°C"

        low_temp:
          name: Turn fan OFF below (°C)
          description: >
            If the temperature drops below this value, the fan will be
            turned OFF. Use a lower value than the ON threshold to
            create hysteresis and avoid flapping.
          default: 50
          selector:
            number:
              min: 20
              max: 85
              step: 1
              unit_of_measurement: "°C"

variables:
  temp_sensor: !input temp_sensor
  fan_switch: !input fan_switch
  high_temp: !input high_temp
  low_temp: !input low_temp

mode: single
max_exceeded: silent

triggers:
  - alias: "Temperature sensor state changed"
    trigger: state
    entity_id: !input temp_sensor

  - alias: "HA restarted — sync fan to current temperature"
    trigger: homeassistant
    event: start

conditions: []

actions:
  - alias: "Evaluate temperature and control fan"
    choose:
      - alias: "Too hot — turn fan ON"
        conditions:
          - condition: numeric_state
            entity_id: !input temp_sensor
            above: !input high_temp
        sequence:
          - alias: "Turn fan ON"
            action: switch.turn_on
            target:
              entity_id: !input fan_switch

      - alias: "Cooled down — turn fan OFF"
        conditions:
          - condition: numeric_state
            entity_id: !input temp_sensor
            below: !input low_temp
        sequence:
          - alias: "Turn fan OFF"
            action: switch.turn_off
            target:
              entity_id: !input fan_switch

      - alias: "Sensor unavailable/unknown — safety fallback, turn fan OFF"
        conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: !input temp_sensor
                state: "unavailable"
              - condition: state
                entity_id: !input temp_sensor
                state: "unknown"
        sequence:
          - alias: "Safety fallback — turn fan OFF"
            action: switch.turn_off
            target:
              entity_id: !input fan_switch
