blueprint:
  name: Voice PE – Resume media after conversation
  domain: automation
  author: Miquel Madalone
  description: >
    RESUME MEDIA AFTER A HOME ASSISTANT VOICE PE CONVERSATION

    🧠 PURPOSE
    This blueprint resumes playback ONLY on the media players that were
    actually playing *before* a Home Assistant Voice PE conversation started.

    It is designed to be used together with a companion automation that:
      - Detects which players were playing.
      - Stores that info in helpers (input_booleans).
      - Pauses/ducks those players while Voice PE is listening/responding.

    This blueprint runs AFTER Voice PE finishes responding and:
      1) Looks at each configured media_player.
      2) Checks if the matching input_boolean "<player_id>_was_playing" is ON.
      3) If yes, resumes playback on that player.
      4) Turns all those helpers OFF so they’re ready for next time.

    🔩 NAMING CONVENTION (IMPORTANT)
    For each media_player you want this blueprint to manage, you must create
    an input_boolean helper that follows this exact pattern:

      media_player.SOMETHING  ->  input_boolean.SOMETHING_was_playing

    Examples:
      media_player.40pfs6009_12           -> input_boolean.40pfs6009_12_was_playing
      media_player.alexa                  -> input_boolean.alexa_was_playing
      media_player.madteevee              -> input_boolean.madteevee_was_playing
      media_player.workshop               -> input_boolean.workshop_was_playing
      media_player.miquel_s_echo_pop      -> input_boolean.miquel_s_echo_pop_was_playing
      media_player.miquel_s_2nd_echo_pop  -> input_boolean.miquel_s_2nd_echo_pop_was_playing

    If a helper does not exist, this automation will log an error for that
    entity, so make sure you create them first.

    🛠 HOW TO CREATE THE HELPERS (UI)
    1. Go to: Settings → Devices & services → Helpers.
    2. Click “+ Create Helper”.
    3. Choose “Toggle” (input_boolean).
    4. Name it something friendly (e.g. “TV was playing”), but set the
       Entity ID to match the convention above:
         - Example: for media_player.madteevee
           Entity ID: input_boolean.madteevee_was_playing
    5. Repeat for each media player you want to support.

    🔁 EXPECTED COMPANION AUTOMATION
    Another automation (e.g. "Voice PE – Mark & Pause media before conversation")
    should:
      - Turn ON input_boolean.<player_id>_was_playing when that player is
        playing and Voice PE starts listening.
      - Pause or duck the media.
    This blueprint ONLY handles the "resume after conversation" part.

    🚀 SETUP CHECKLIST
    1. Create all needed input_boolean.<player_id>_was_playing helpers.
    2. Import this blueprint.
    3. Create a new automation from this blueprint.
    4. Select:
       - The Voice PE satellite(s) you want to monitor.
       - All media_player entities whose playback you want to resume.
    5. Make sure your companion "mark & pause" automation uses the same
       naming pattern for the helpers.

  input:
    satellites:
      name: Voice PE satellites to monitor
      description: >
        Select the Home Assistant Voice PE satellite(s) that should trigger
        the resume action when they finish responding. This blueprint will
        trigger when any selected satellite goes from state "responding"
        back to "idle".
      selector:
        entity:
          domain: assist_satellite
          multiple: true

    media_players:
      name: Media players to resume
      description: >
        Select ALL media_player entities that should be resumed after a Voice
        PE conversation. For EACH selected media player, you must create a
        helper input_boolean with this pattern:
          input_boolean.<media_player_entity_id_without_prefix>_was_playing

        Example:
          media_player.madteevee -> input_boolean.madteevee_was_playing

        The companion automation will set those helpers ON/OFF, and this
        blueprint will only resume players whose helper is ON.
      selector:
        entity:
          domain: media_player
          multiple: true

trigger:
  - platform: state
    entity_id: !input satellites
    from: responding
    to: idle

variables:
  media_players_list: !input media_players

condition: []

action:
  # 1) For each configured media player:
  #    - Build the corresponding helper entity_id:
  #        input_boolean.<player_id_without_media_player.>_was_playing
  #    - If that helper is ON, resume playback on the player.
  - repeat:
      for_each: "{{ media_players_list }}"
      sequence:
        - variables:
            player: "{{ repeat.item }}"
            player_id: "{{ player.split('.')[1] }}"
            helper: "{{ 'input_boolean.' ~ player_id ~ '_was_playing' }}"
        - choose:
            - conditions:
                - condition: state
                  entity_id: "{{ helper }}"
                  state: "on"
              sequence:
                - service: media_player.media_play
                  target:
                    entity_id: "{{ player }}"

  # 2) After resuming, turn OFF all helper booleans so they are ready
  #    for the next Voice PE interaction.
  - repeat:
      for_each: "{{ media_players_list }}"
      sequence:
        - variables:
            player: "{{ repeat.item }}"
            player_id: "{{ player.split('.')[1] }}"
            helper: "{{ 'input_boolean.' ~ player_id ~ '_was_playing' }}"
        - service: input_boolean.turn_off
          target:
            entity_id: "{{ helper }}"

mode: single
