blueprint:
  name: Voice PE – Restore media volumes after conversation (Alexa-safe, 8 players)
  description: >
    Restores the original volumes of your media players after a Voice PE
    conversation has finished.

    HOW IT WORKS
    ------------
    - Triggers whenever any selected Assist Satellite returns to 'idle'
      from any other state (listening / processing / responding / cancelled).
      This fixes cases where you cancel quickly with a second wake word or
      the hardware button and the idle state is very short.

    - Duck/restore is tied only to:
        - satellite goes idle
        - ducking flag is ON

    - If the ducking flag (input_boolean) is ON:
        - For each configured media player:
            * Read the stored volume from its input_number helper.
            * Apply that value back to the media player.
        - Turn the ducking flag OFF so the next conversation will store
          volumes again.

    COMBINED WITH THE DUCK BLUEPRINT
    --------------------------------
    - The duck blueprint still:
        - Stores Alexa volumes in an Alexa-safe way.
        - Ducks only when Assist goes idle → listening/responding.
    - This restore blueprint now reliably restores for:
        - normal conversations
        - short or cancelled interactions
        - "never mind" / double wake word / button cancels.

  domain: automation
  source_url: https://github.com/mmadalone/HA-Master-Repo/blob/main/automation/voice_pe_restore_media_volumes.yaml
  homeassistant:
    min_version: "2024.10.0"
  # version: 1.0.0

  input:
    # ── Section 1: Core Settings ─────────────────────────────────────
    core_settings:
      name: Core Settings
      icon: mdi:cog
      description: >
        Required settings — satellites, ducking flag, restore delay, and
        the primary announcement player.
      collapsed: false
      input:
        satellites:
          name: Voice PE Assist Satellites
          description: >
            Select the same Assist Satellites you used in the duck blueprint.
            The automation runs when ANY of them returns to 'idle' from
            any other state.
          default: []
          selector:
            entity:
              domain: assist_satellite
              multiple: true

        ducking_flag:
          name: Ducking active flag (input_boolean)
          description: >
            The same input_boolean used in the duck blueprint. When this is
            ON, volumes will be restored and the flag will be turned OFF
            afterwards.
          default: []
          selector:
            entity:
              domain: input_boolean

        restore_delay:
          name: Restore delay (seconds)
          description: >
            How long the satellite must stay idle before restoring volumes.
            Prevents volume bouncing during multi-turn conversations where
            the satellite briefly returns to idle between turns. 2–3 seconds
            works well for most setups.
          default: 2
          selector:
            number:
              min: 0
              max: 10
              step: 0.5
              unit_of_measurement: s
              mode: slider

        announcement_player_1:
          name: Announcement player 1
          description: >
            Primary Voice PE announcement player to restore after TTS.
            Must match the duck blueprint configuration.
          default: []
          selector:
            entity:
              domain: media_player

        announcement_player_1_volume_helper:
          name: Announcement player 1 – volume helper (input_number)
          description: >
            Same input_number helper used by the duck blueprint for
            Announcement player 1.
          default: []
          selector:
            entity:
              domain: input_number

    # ── Section 2: Additional Announcement Players ───────────────────
    additional_announcement_players:
      name: Additional Announcement Players
      icon: mdi:bullhorn
      description: >
        Optional Voice PE announcement players 2–4. Leave at defaults if
        unused.
      collapsed: true
      input:
        announcement_player_2:
          name: Announcement player 2
          description: >
            Optional second Voice PE announcement player.
          default: media_player.dummy_placeholder
          selector:
            entity:
              domain: media_player

        announcement_player_2_volume_helper:
          name: Announcement player 2 – volume helper
          description: >
            Volume helper for Announcement player 2.
          default: input_number.dummy_placeholder
          selector:
            entity:
              domain: input_number

        announcement_player_3:
          name: Announcement player 3
          description: >
            Optional third Voice PE announcement player.
          default: media_player.dummy_placeholder
          selector:
            entity:
              domain: media_player

        announcement_player_3_volume_helper:
          name: Announcement player 3 – volume helper
          description: >
            Volume helper for Announcement player 3.
          default: input_number.dummy_placeholder
          selector:
            entity:
              domain: input_number

        announcement_player_4:
          name: Announcement player 4
          description: >
            Optional fourth Voice PE announcement player.
          default: media_player.dummy_placeholder
          selector:
            entity:
              domain: media_player

        announcement_player_4_volume_helper:
          name: Announcement player 4 – volume helper
          description: >
            Volume helper for Announcement player 4.
          default: input_number.dummy_placeholder
          selector:
            entity:
              domain: input_number

    # ── Section 3: Media Players 1–4 ────────────────────────────────
    media_players_1_4:
      name: Media Players 1–4
      icon: mdi:animation-play
      description: >
        First group of media players whose volumes should be restored.
        Leave at defaults if a slot is unused.
      collapsed: true
      input:
        media_player_1:
          name: Media player 1
          description: First media player to restore.
          default: media_player.dummy_placeholder
          selector:
            entity:
              domain: media_player

        media_player_1_volume_helper:
          name: Media player 1 – volume helper
          description: Volume helper for Media player 1.
          default: input_number.dummy_placeholder
          selector:
            entity:
              domain: input_number

        media_player_2:
          name: Media player 2
          description: Second media player to restore.
          default: media_player.dummy_placeholder
          selector:
            entity:
              domain: media_player

        media_player_2_volume_helper:
          name: Media player 2 – volume helper
          description: Volume helper for Media player 2.
          default: input_number.dummy_placeholder
          selector:
            entity:
              domain: input_number

        media_player_3:
          name: Media player 3
          description: Third media player to restore.
          default: media_player.dummy_placeholder
          selector:
            entity:
              domain: media_player

        media_player_3_volume_helper:
          name: Media player 3 – volume helper
          description: Volume helper for Media player 3.
          default: input_number.dummy_placeholder
          selector:
            entity:
              domain: input_number

        media_player_4:
          name: Media player 4
          description: Fourth media player to restore.
          default: media_player.dummy_placeholder
          selector:
            entity:
              domain: media_player

        media_player_4_volume_helper:
          name: Media player 4 – volume helper
          description: Volume helper for Media player 4.
          default: input_number.dummy_placeholder
          selector:
            entity:
              domain: input_number

    # ── Section 4: Media Players 5–8 ────────────────────────────────
    media_players_5_8:
      name: Media Players 5–8
      icon: mdi:animation-play
      description: >
        Second group of media players whose volumes should be restored.
        Leave at defaults if a slot is unused.
      collapsed: true
      input:
        media_player_5:
          name: Media player 5
          description: Fifth media player to restore.
          default: media_player.dummy_placeholder
          selector:
            entity:
              domain: media_player

        media_player_5_volume_helper:
          name: Media player 5 – volume helper
          description: Volume helper for Media player 5.
          default: input_number.dummy_placeholder
          selector:
            entity:
              domain: input_number

        media_player_6:
          name: Media player 6
          description: Sixth media player to restore.
          default: media_player.dummy_placeholder
          selector:
            entity:
              domain: media_player

        media_player_6_volume_helper:
          name: Media player 6 – volume helper
          description: Volume helper for Media player 6.
          default: input_number.dummy_placeholder
          selector:
            entity:
              domain: input_number

        media_player_7:
          name: Media player 7
          description: Seventh media player to restore.
          default: media_player.dummy_placeholder
          selector:
            entity:
              domain: media_player

        media_player_7_volume_helper:
          name: Media player 7 – volume helper
          description: Volume helper for Media player 7.
          default: input_number.dummy_placeholder
          selector:
            entity:
              domain: input_number

        media_player_8:
          name: Media player 8
          description: Eighth media player to restore.
          default: media_player.dummy_placeholder
          selector:
            entity:
              domain: media_player

        media_player_8_volume_helper:
          name: Media player 8 – volume helper
          description: Volume helper for Media player 8.
          default: input_number.dummy_placeholder
          selector:
            entity:
              domain: input_number

mode: single
max_exceeded: silent

# ── Variables ──────────────────────────────────────────────────────
# Build a list of player/helper pairs for repeat: for_each iteration.
# Dummy placeholders are filtered out at runtime.
variables:
  players:
    - player: !input announcement_player_1
      helper: !input announcement_player_1_volume_helper
    - player: !input announcement_player_2
      helper: !input announcement_player_2_volume_helper
    - player: !input announcement_player_3
      helper: !input announcement_player_3_volume_helper
    - player: !input announcement_player_4
      helper: !input announcement_player_4_volume_helper
    - player: !input media_player_1
      helper: !input media_player_1_volume_helper
    - player: !input media_player_2
      helper: !input media_player_2_volume_helper
    - player: !input media_player_3
      helper: !input media_player_3_volume_helper
    - player: !input media_player_4
      helper: !input media_player_4_volume_helper
    - player: !input media_player_5
      helper: !input media_player_5_volume_helper
    - player: !input media_player_6
      helper: !input media_player_6_volume_helper
    - player: !input media_player_7
      helper: !input media_player_7_volume_helper
    - player: !input media_player_8
      helper: !input media_player_8_volume_helper

# ── Triggers ───────────────────────────────────────────────────────
triggers:
  - id: "satellite_idle"
    alias: "Satellite returned to idle"
    trigger: state
    entity_id: !input satellites
    # No 'from:' filter — catches idle from ALL states (listening,
    # responding, cancelled, etc.) to handle every exit path.
    to: idle
    for:
      seconds: !input restore_delay

# ── Conditions ─────────────────────────────────────────────────────
# Intentionally empty — ducking-flag gate lives inside the choose block.
conditions: []

# ── Actions ────────────────────────────────────────────────────────
actions:
  - alias: "Check if ducking is active"
    choose:
      - conditions:
          - condition: state
            entity_id: !input ducking_flag
            state: "on"
        sequence:
          - alias: "Restore volumes for all configured players"
            repeat:
              for_each: >-
                {{ players
                   | rejectattr('player', 'search', 'dummy_placeholder')
                   | list }}
              sequence:
                - alias: "Restore volume → {{ repeat.item.player }}"
                  action: media_player.volume_set
                  continue_on_error: true
                  target:
                    entity_id: "{{ repeat.item.player }}"
                  data:
                    volume_level: "{{ states(repeat.item.helper) | float(0) }}"

          # Wait for volume sync cooldown so the sync blueprint sees the
          # flag is still ON and skips the restore volume change. 3 seconds
          # covers the default 1 s cooldown plus a safety buffer.
          # COUPLING: voice_pe_duck_media_volumes.yaml sync cooldown.
          # If that blueprint's cooldown changes, update this delay.
          - alias: "Wait for volume sync cooldown (3 s)"
            delay:
              seconds: 3

          # Clear ducking flag so next conversation will store again
          - alias: "Clear ducking flag"
            action: input_boolean.turn_off
            target:
              entity_id: !input ducking_flag
    default: []
