blueprint:
  name: "Voice PE – Duck Media Volumes While Listening (Alexa-Safe)"
  description: >
    ![Image](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/voice_pe_duck_media_volumes-header.jpeg)


    v2.0.0 · Automatically lowers (ducks) the volume of your chosen media
    players whenever a Voice PE satellite begins a voice interaction.

    Supports up to 8 media players and 4 announcement players with
    Alexa-safe volume storage — preserves last known volume when an
    integration temporarily loses volume_level after a HA restart.

    Triggers on idle → listening (wake word) or idle → responding
    (announce / ask_question / script-initiated).
  source_url: "https://github.com/mmadalone/HA-Master-Repo/blob/main/automation/voice_pe_duck_media_volumes.yaml"
  domain: automation

  input:
    section_core:
      name: "Core Configuration"
      icon: mdi:microphone-settings
      collapsed: false
      input:
        satellites:
          name: "Voice PE Assist Satellites"
          description: >
            Select all Assist Satellite entities for your Voice PE devices.
            Triggers when ANY selected satellite transitions from idle to
            listening or responding.
          default:
          selector:
            entity:
              domain: assist_satellite
              multiple: true

        ducking_flag:
          name: "Ducking active flag (input_boolean)"
          description: >
            input_boolean helper that marks an active ducking session.
            Prevents overwriting stored volumes on repeated triggers
            within the same voice conversation.
          default:
          selector:
            entity:
              domain: input_boolean

        duck_volume_level:
          name: "Ducked volume level"
          description: >
            Volume each playing media player is set to while Voice PE
            is active (0.0–1.0).
          default: 0.15
          selector:
            number:
              min: 0.0
              max: 1.0
              step: 0.01
              mode: slider

        announcement_volume:
          name: "Announcement volume level"
          description: >
            Volume for Voice PE TTS output during interaction. Overrides
            the ducked volume on announcement players so the assistant
            speaks at a comfortable level (0.0–1.0).
          default: 0.65
          selector:
            number:
              min: 0.0
              max: 1.0
              step: 0.01
              mode: slider

    section_announcement:
      name: "Announcement Players"
      icon: mdi:bullhorn
      collapsed: true
      description: >
        Voice PE media players whose volume is boosted for TTS output.
        Each player needs a paired input_number helper (0.0–1.0 range)
        to store its pre-boost volume. Configure only the slots you need.
      input:
        announcement_player_1:
          name: "Announcement player 1"
          description: >
            First Voice PE media player for TTS boost.
          default:
          selector:
            entity:
              domain: media_player

        announcement_player_1_volume_helper:
          name: "Announcement player 1 – volume helper"
          description: >
            input_number helper storing pre-boost volume for player 1.
          default:
          selector:
            entity:
              domain: input_number

        announcement_player_2:
          name: "Announcement player 2"
          description: >
            Second Voice PE media player for TTS boost.
          default:
          selector:
            entity:
              domain: media_player

        announcement_player_2_volume_helper:
          name: "Announcement player 2 – volume helper"
          description: >
            input_number helper storing pre-boost volume for player 2.
          default:
          selector:
            entity:
              domain: input_number

        announcement_player_3:
          name: "Announcement player 3"
          description: >
            Third Voice PE media player for TTS boost.
          default:
          selector:
            entity:
              domain: media_player

        announcement_player_3_volume_helper:
          name: "Announcement player 3 – volume helper"
          description: >
            input_number helper storing pre-boost volume for player 3.
          default:
          selector:
            entity:
              domain: input_number

        announcement_player_4:
          name: "Announcement player 4"
          description: >
            Fourth Voice PE media player for TTS boost.
          default:
          selector:
            entity:
              domain: media_player

        announcement_player_4_volume_helper:
          name: "Announcement player 4 – volume helper"
          description: >
            input_number helper storing pre-boost volume for player 4.
          default:
          selector:
            entity:
              domain: input_number

    section_media_players:
      name: "Media Players to Duck"
      icon: mdi:volume-minus
      collapsed: true
      description: >
        Media players whose volume is lowered during voice interactions
        (TV, Sonos, Alexa groups, etc.). Each player needs a paired
        input_number helper (0.0–1.0 range) to store its pre-duck
        volume. Configure only the slots you need.
      input:
        media_player_1:
          name: "Media player 1"
          description: >
            First media player to duck.
          default:
          selector:
            entity:
              domain: media_player

        media_player_1_volume_helper:
          name: "Media player 1 – volume helper"
          description: >
            input_number helper storing pre-duck volume for player 1.
          default:
          selector:
            entity:
              domain: input_number

        media_player_2:
          name: "Media player 2"
          description: >
            Second media player to duck.
          default:
          selector:
            entity:
              domain: media_player

        media_player_2_volume_helper:
          name: "Media player 2 – volume helper"
          description: >
            input_number helper storing pre-duck volume for player 2.
          default:
          selector:
            entity:
              domain: input_number

        media_player_3:
          name: "Media player 3"
          description: >
            Third media player to duck.
          default:
          selector:
            entity:
              domain: media_player

        media_player_3_volume_helper:
          name: "Media player 3 – volume helper"
          description: >
            input_number helper storing pre-duck volume for player 3.
          default:
          selector:
            entity:
              domain: input_number

        media_player_4:
          name: "Media player 4"
          description: >
            Fourth media player to duck.
          default:
          selector:
            entity:
              domain: media_player

        media_player_4_volume_helper:
          name: "Media player 4 – volume helper"
          description: >
            input_number helper storing pre-duck volume for player 4.
          default:
          selector:
            entity:
              domain: input_number

        media_player_5:
          name: "Media player 5"
          description: >
            Fifth media player to duck.
          default:
          selector:
            entity:
              domain: media_player

        media_player_5_volume_helper:
          name: "Media player 5 – volume helper"
          description: >
            input_number helper storing pre-duck volume for player 5.
          default:
          selector:
            entity:
              domain: input_number

        media_player_6:
          name: "Media player 6"
          description: >
            Sixth media player to duck.
          default:
          selector:
            entity:
              domain: media_player

        media_player_6_volume_helper:
          name: "Media player 6 – volume helper"
          description: >
            input_number helper storing pre-duck volume for player 6.
          default:
          selector:
            entity:
              domain: input_number

        media_player_7:
          name: "Media player 7"
          description: >
            Seventh media player to duck.
          default:
          selector:
            entity:
              domain: media_player

        media_player_7_volume_helper:
          name: "Media player 7 – volume helper"
          description: >
            input_number helper storing pre-duck volume for player 7.
          default:
          selector:
            entity:
              domain: input_number

        media_player_8:
          name: "Media player 8"
          description: >
            Eighth media player to duck.
          default:
          selector:
            entity:
              domain: media_player

        media_player_8_volume_helper:
          name: "Media player 8 – volume helper"
          description: >
            input_number helper storing pre-duck volume for player 8.
          default:
          selector:
            entity:
              domain: input_number

mode: single

# ── Variables ──────────────────────────────────────────────────────
# Raw !input bindings + computed lists for repeat: for_each
variables:
  duck_volume_level: !input duck_volume_level
  announcement_vol: !input announcement_volume
  # Media player raw bindings
  _mp1: !input media_player_1
  _mp1_h: !input media_player_1_volume_helper
  _mp2: !input media_player_2
  _mp2_h: !input media_player_2_volume_helper
  _mp3: !input media_player_3
  _mp3_h: !input media_player_3_volume_helper
  _mp4: !input media_player_4
  _mp4_h: !input media_player_4_volume_helper
  _mp5: !input media_player_5
  _mp5_h: !input media_player_5_volume_helper
  _mp6: !input media_player_6
  _mp6_h: !input media_player_6_volume_helper
  _mp7: !input media_player_7
  _mp7_h: !input media_player_7_volume_helper
  _mp8: !input media_player_8
  _mp8_h: !input media_player_8_volume_helper
  # Announcement player raw bindings
  _ap1: !input announcement_player_1
  _ap1_h: !input announcement_player_1_volume_helper
  _ap2: !input announcement_player_2
  _ap2_h: !input announcement_player_2_volume_helper
  _ap3: !input announcement_player_3
  _ap3_h: !input announcement_player_3_volume_helper
  _ap4: !input announcement_player_4
  _ap4_h: !input announcement_player_4_volume_helper
  # Computed list — media players (filters out unconfigured slots)
  media_players: >-
    {%- set ns = namespace(r=[]) -%}
    {%- set pairs = [
      {'entity': _mp1, 'helper': _mp1_h},
      {'entity': _mp2, 'helper': _mp2_h},
      {'entity': _mp3, 'helper': _mp3_h},
      {'entity': _mp4, 'helper': _mp4_h},
      {'entity': _mp5, 'helper': _mp5_h},
      {'entity': _mp6, 'helper': _mp6_h},
      {'entity': _mp7, 'helper': _mp7_h},
      {'entity': _mp8, 'helper': _mp8_h}
    ] -%}
    {%- for p in pairs -%}
      {%- if p.entity not in [none, '', 'unknown', 'unavailable']
         and p.helper not in [none, '', 'unknown', 'unavailable'] -%}
        {%- set ns.r = ns.r + [p] -%}
      {%- endif -%}
    {%- endfor -%}
    {{ ns.r }}
  # Computed list — announcement players (filters out unconfigured slots)
  announcement_players: >-
    {%- set ns = namespace(r=[]) -%}
    {%- set pairs = [
      {'entity': _ap1, 'helper': _ap1_h},
      {'entity': _ap2, 'helper': _ap2_h},
      {'entity': _ap3, 'helper': _ap3_h},
      {'entity': _ap4, 'helper': _ap4_h}
    ] -%}
    {%- for p in pairs -%}
      {%- if p.entity not in [none, '', 'unknown', 'unavailable']
         and p.helper not in [none, '', 'unknown', 'unavailable'] -%}
        {%- set ns.r = ns.r + [p] -%}
      {%- endif -%}
    {%- endfor -%}
    {{ ns.r }}

# ── Triggers ───────────────────────────────────────────────────────
triggers:
  # Wake word: user says "Hey Rick" / "Hey Quark" → idle → listening
  - alias: "Satellite starts listening (wake word)"
    trigger: state
    entity_id: !input satellites
    from: idle
    to: listening

  # Script-initiated: announce / ask_question → idle → responding
  - alias: "Satellite starts responding (announce/script)"
    trigger: state
    entity_id: !input satellites
    from: idle
    to: responding

conditions: []

# ── Actions ────────────────────────────────────────────────────────
actions:
  # ─── Phase 1: Store volumes (first trigger only) ─────────────────
  - alias: "Phase 1 — Store volumes on first trigger (skip if already ducking)"
    if:
      - condition: state
        entity_id: !input ducking_flag
        state: "off"
    then:
      - alias: "Set ducking flag ON"
        action: input_boolean.turn_on
        target:
          entity_id: !input ducking_flag

      - alias: "Store media player volumes (Alexa-safe)"
        repeat:
          for_each: "{{ media_players }}"
          sequence:
            - alias: "Store volume — {{ repeat.item.entity }}"
              action: input_number.set_value
              continue_on_error: true
              target:
                entity_id: "{{ repeat.item.helper }}"
              data:
                value: >-
                  {% set vol = state_attr(repeat.item.entity, 'volume_level') %}
                  {% set prev = states(repeat.item.helper) | default('0') %}
                  {% if vol is not none %}
                    {{ vol | float(0) }}
                  {% elif prev not in ['unknown', 'unavailable', 'none', '', None] %}
                    {{ prev | float(0) }}
                  {% else %}
                    {{ 0 }}
                  {% endif %}

      - alias: "Store announcement player volumes (Alexa-safe)"
        repeat:
          for_each: "{{ announcement_players }}"
          sequence:
            - alias: "Store announcement volume — {{ repeat.item.entity }}"
              action: input_number.set_value
              continue_on_error: true
              target:
                entity_id: "{{ repeat.item.helper }}"
              data:
                value: >-
                  {% set vol = state_attr(repeat.item.entity, 'volume_level') %}
                  {% set prev = states(repeat.item.helper) | default('0') %}
                  {% if vol is not none %}
                    {{ vol | float(0) }}
                  {% elif prev not in ['unknown', 'unavailable', 'none', '', None] %}
                    {{ prev | float(0) }}
                  {% else %}
                    {{ 0 }}
                  {% endif %}

  # ─── Phase 2: Duck playing media players ─────────────────────────
  - alias: "Phase 2 — Duck volumes on all playing media players"
    repeat:
      for_each: "{{ media_players }}"
      sequence:
        - alias: "Duck {{ repeat.item.entity }} (if playing)"
          if:
            - condition: template
              value_template: "{{ is_state(repeat.item.entity, 'playing') }}"
          then:
            - alias: "Set ducked volume on {{ repeat.item.entity }}"
              action: media_player.volume_set
              continue_on_error: true
              target:
                entity_id: "{{ repeat.item.entity }}"
              data:
                volume_level: "{{ duck_volume_level }}"

  # ─── Phase 3: Boost announcement players for TTS ─────────────────
  - alias: "Phase 3 — Set announcement players to TTS volume"
    repeat:
      for_each: "{{ announcement_players }}"
      sequence:
        - alias: "Boost {{ repeat.item.entity }} to announcement volume"
          action: media_player.volume_set
          continue_on_error: true
          target:
            entity_id: "{{ repeat.item.entity }}"
          data:
            volume_level: "{{ announcement_vol }}"
