blueprint:
  name: "Wake-up guard – mobile Snooze/Stop handler (with player stop)"
  author: madalone
  homeassistant:
    min_version: "2024.10.0"
  description: '![Header](https://raw.githubusercontent.com/mmadalone/HA-Master-Repo/main/images/header/wakeup_guard_mobile_notify-header.jpeg)

    # Wake-up guard – mobile Snooze/Stop handler

    Handles Snooze/Stop actions for the "Wake-up guard" automation.
    Reacts to Companion app notification actions (GUARD_SNOOZE / GUARD_STOP)
    or the Snooze/Stop input_booleans being turned ON (e.g. from a dashboard button).

    Turns on the matching input_boolean so the main wake-up blueprint takes the
    right branch, then immediately stops TTS and (optionally) music players.

    Use together with the Wake-up guard blueprint — configure matching toggles
    and notification action IDs in both.

    ### Recent changes

    - **v3:** Refactored to single action path, added continue_on_error, section polish

    - **v2:** Full style-guide compliance — modern syntax, collapsible inputs, aliases

    - **v1:** Initial version'

  domain: automation

  input:
    # ===========================================================================
    # ① TOGGLES & ENTITIES
    # ===========================================================================
    toggles_and_entities:
      name: "① Toggles & entities"
      icon: mdi:toggle-switch
      description: Shared input_booleans and media players used by the wake-up system.
      input:
        snooze_toggle:
          name: Snooze toggle
          description: >
            Same input_boolean as "Snooze toggle" in Wake-up guard.
            Will be turned ON when Snooze is triggered.
          selector:
            entity:
              domain: input_boolean

        stop_toggle:
          name: Stop toggle
          description: >
            Same input_boolean as "Stop toggle" in Wake-up guard.
            Will be turned ON when Stop is triggered.
          selector:
            entity:
              domain: input_boolean

        tts_player:
          name: TTS player (output)
          description: >
            Media player used by TTS (same as "Media player for voice"
            in the main wake-up blueprint).
          selector:
            entity:
              domain: media_player

        music_players:
          name: Music players to stop (optional)
          description: >
            Any media players that might be playing the wake-up music
            (Music Assistant, SpotifyPlus, etc.). Leave empty if not used.
          default: []
          selector:
            entity:
              domain: media_player
              multiple: true

    # ===========================================================================
    # ② NOTIFICATION ACTION IDS
    # ===========================================================================
    notification_action_ids:
      name: "② Notification action IDs"
      icon: mdi:bell-ring
      description: Action strings that must match the Companion app notification actions.
      input:
        snooze_action_id:
          name: Snooze action ID
          description: >
            Notification action ID for Snooze. Must match the "action" field
            in the notification data sent by Wake-up guard.
          default: "GUARD_SNOOZE"
          selector:
            select:
              custom_value: true
              options:
                - "GUARD_SNOOZE"

        stop_action_id:
          name: Stop action ID
          description: >
            Notification action ID for Stop. Must match the "action" field
            in the notification data sent by Wake-up guard.
          default: "GUARD_STOP"
          selector:
            select:
              custom_value: true
              options:
                - "GUARD_STOP"

mode: restart

variables:
  snooze_toggle: !input snooze_toggle
  stop_toggle: !input stop_toggle
  tts_player: !input tts_player
  music_players: !input music_players

triggers:
  - alias: "Snooze — mobile notification action"
    trigger: event
    event_type: mobile_app_notification_action
    event_data:
      action: !input snooze_action_id
    id: snooze

  - alias: "Stop — mobile notification action"
    trigger: event
    event_type: mobile_app_notification_action
    event_data:
      action: !input stop_action_id
    id: stop

  - alias: "Snooze — input_boolean toggled on"
    trigger: state
    entity_id: !input snooze_toggle
    to: "on"
    id: snooze_toggle

  - alias: "Stop — input_boolean toggled on"
    trigger: state
    entity_id: !input stop_toggle
    to: "on"
    id: stop_toggle

conditions: []

actions:
  - alias: "Resolve which toggle to activate based on trigger"
    variables:
      target_toggle: >-
        {% if trigger.id in ['snooze', 'snooze_toggle'] %}
          {{ snooze_toggle }}
        {% else %}
          {{ stop_toggle }}
        {% endif %}

  - alias: "Turn on the matching toggle for the main wake-up blueprint"
    action: input_boolean.turn_on
    target:
      entity_id: "{{ target_toggle }}"

  - alias: "Stop TTS player immediately"
    continue_on_error: true
    action: media_player.media_stop
    target:
      entity_id: !input tts_player

  - alias: "Stop music players — queue destruction intentional (wake-up context)"
    continue_on_error: true
    action: media_player.media_stop
    target:
      entity_id: !input music_players
